### ISSUE TITLE
[Feat]: Search notebooks

### ISSUE THREAD

**Issue by jfsicilia** [rxliuli/joplin-utils#103]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

No easy way to find a **notebook**.

### Describe the solution you'd like

There's an option to `find notes` but I can not find an easy way to find **notebooks** (I must navigate the notebooks tree if I want to check the notes dangling from a specific notebook). 

### Describe alternatives you've considered

It would be great to have this possibility, either creating a `find notebooks` similar to `find notes`, or just use `find notes` and specify a notebook by prefixing a `@` like in the "Go to Anything" of the Joplin Desktop program.

**Comment by rxliuli** [comment]
Right-click Search on the notebook, or directly enter `notebook:"[notebook]" [keyword]`

**Comment by jfsicilia** [comment]
Perfect, thanks.
