### ISSUE TITLE
[Feat]: `joplin.token` from environment variable

### ISSUE THREAD

**Issue by skwde** [rxliuli/joplin-utils#107]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

There are actually several problems related with `joplin.token` via `settings.json` with `sync` on.

- The token needs to be retrieved from the Joplin application on each machine and entered each time when using the extension on a different machine. In Joplin we cannot set the token to use.
- The token is synchronized with an external party (Microsoft / github) or in a git repository depending on where `joplin.token` is set.

The latter is only a minor problem because the token is only usable on the local machine (to my understanding).

### Describe the solution you'd like

Above problems would be solved by optionally retrieving `joplin.token` from an environment variable, e.g. `JOPLIN_VSCODE_TOKEN`.

### Describe alternatives you've considered

Resetting the token everytime I switch machines is time consuming and annoying.
Use of the Joplin app is unfortunately more convenient in that case.

**Comment by rxliuli** [comment]
Known issues, reference: https://joplin-utils.rxliuli.com/en-US/joplin-vscode-plugin/faq.html#how-to-use-the-plugin-with-two-synchronized-vscode-configurations
