### ISSUE TITLE
[Bug]: 和PicGo插件冲突，picgo在使用浏览文件上传和剪贴板上传的时候会返回本地路径。

### ISSUE THREAD

**Issue by leeh11** [rxliuli/joplin-utils#15]
### 确认事项

- [X] 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### 发生错误的工具/包

joplin-vscode-plugin

### 描述这个错误

picgo在使用浏览文件上传和剪贴板上传的时候会将图片保存到joplin目录下的resources目录中。

禁用 joplin插件后picgo插件功能就正常了。

![image](https://user-images.githubusercontent.com/24563847/133256698-5d209e77-f09a-427b-8056-5d6a24b1a8ce.png)

### 复现错误的步骤

1. vscode 安装 picgo插件
2. 安装joplin插件
3. 编辑md
4. picgo使用浏览文件上传和剪贴板上传图片。
5. picgo返回本地路径。图片页保存在本地。

**Comment by rxliuli** [comment]
参考 faq: <https://joplin-utils.rxliuli.com/zh/joplin-vscode-plugin/guide/feature.html#%E7%B2%98%E8%B4%B4%E5%9B%BE%E7%89%87>
