### ISSUE TITLE
[Bug]: joplin-blog: no notes are processed

### ISSUE THREAD

**Issue by huyz** [rxliuli/joplin-utils#18]
### 

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-blog

### Describe the bug

I can't get started on joplin-blog on macOS 10.15.7.  Nothing happens.

I followed the instructions and I just get:

```
$ joplin-blog wiki
    _             _ _             _     _
   (_) ___  _ __ | (_)_ __       | |__ | | ___   __ _
   | |/ _ \| '_ \| | | '_ \ _____| '_ \| |/ _ \ / _` |
   | | (_) | |_) | | | | | |_____| |_) | | (_) | (_| |
  _/ |\___/| .__/|_|_|_| |_|     |_.__/|_|\___/ \__, |
 |__/      |_|                                  |___/
⚠ No notes to be processed
  Start filtering joplin notes
✨  Done in 1.75s.
```

What am I doing wrong?

### Steps to reproduce the behavior

Just follow the instructions in the README.

Here's my `package.json`:
```
❯ cat package.json
{
  "scripts": {
    "gen": "joplin-blog wiki"
  },
  "devDependencies": {
    "joplin-blog": "^0.7.0"
  }
}
```

Here's my `.joplin-blog.json`:
```
❯ cat .joplin-blog.json
{
  "type": "vuepress",
  "language": "en",
  "rootPath": ".",
  "joplinProfilePath": "/Users/huy/.config/joplin-desktop",
  "token": "c8a14932....846490",
  "port": 41184,
  "tag": "wiki"
}
```

**Comment by rxliuli** [comment]
You need to specify which notes need to be exported. If you specify the wiki tag in your configuration above, then only the notes with the wiki tag will be exported. You can select more notes in joplin and set the tag to wiki

**Comment by huyz** [comment]
Oh I see. I didn't understand what the `tag` option was for.  I thought it meant that the output would be tagged.
Maybe in the README, you can change the description from "joplin's blog tag" to "filter the notes to only these that have the specified tag".

What if I wanted to export all my notes?  Is that possible, or do I have to tag them all?
It would be nice if the default was to publish all of the notes. 
So the description would become: "filter the notes to only these that have the specified tag. The default is process all notes"

**Comment by rxliuli** [comment]
Setting `"tag": ""` means no filtering

**Comment by huyz** [comment]
> Set `"tag": ""` to export all notes

Oh great, that worked.  Thanks.

I had tried deleting the entire line but that didn't work.  So, I imagine that `"tag": undefined` or missing `tag` field could be made to work just like `"tag": ""`, which would be less surprising.

**Comment by rxliuli** [comment]
> > Set `"tag": ""` to export all notes
> 
> Oh great, that worked. Thanks.
> 
> I had tried deleting the entire line but that didn't work. So, I imagine that `"tag": undefined` or missing `tag` field could be made to work just like `"tag": ""`, which would be less surprising.

Exporting all notes may be risky in my opinion, so I may be reluctant to use it as the default value. but thank you for your suggestions on the documentation

**Comment by huyz** [comment]
Good point; I understand that is risky.

So maybe if the `tag` is `undefined`, then you can print an error message to the user:
> For safety, the `tag` setting must be configured. If you want to process all notes, then set `tag` to the empty string `""`
