### ISSUE TITLE
[Feat]: host specific joplin token

### ISSUE THREAD

**Issue by andre68723** [rxliuli/joplin-utils#25]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

Using VSCode on 2 different machines work + home with [settings sync](https://code.visualstudio.com/docs/editor/settings-sync)

As the token is generated by Joplin is immutable + individual the extension works only on one machine - the one with the matching token.

### Describe the solution you'd like

ability to enter hostname:token instead of token only

### Describe alternatives you've considered

none found

**Comment by rxliuli** [comment]
In fact, if you want, you can modify the tokens on the two machines to be the same, mainly by viewing the settings.json configuration of your joplin configuration directory, and modifying the `api.token` in it. By the way, windows The address above is *C:\Users\<username>\.config\joplin-desktop*

**Comment by andre68723** [comment]
indeed, not immutable.

On mac it is
```
$ cat ~/.config/joplin-desktop/settings.json |grep api.token
	"api.token": "foo`
```

eventually you can mention it on the docu to maintain the same api key as solution for working with >1  host?

**Comment by rxliuli** [comment]
> indeed, not immutable.
> 
> On mac it is
> 
> ```
> $ cat ~/.config/joplin-desktop/settings.json |grep api.token
> 	"api.token": "foo`
> ```
> 
> eventually you can mention it on the docu to maintain the same api key as solution for working with >1 host?

I will add this in the documentation FAQ later, if you want, you can also try to modify it.

https://github.com/rxliuli/joplin-utils/blob/master/website/docs/joplin-vscode-plugin/guide/faq.md

**Comment by andre68723** [comment]
Oh there is a FAQ, wasn't aware of it.

Maybe link the FAQ also on this page to increase chances of finding it? 
https://github.com/rxliuli/joplin-utils/blob/master/website/docs/joplin-vscode-plugin/README.md

**Comment by rxliuli** [comment]
In fact, we created a website to display documents, which contains all the links

https://joplin-utils.rxliuli.com/joplin-vscode-plugin/#overview

**Comment by andre68723** [comment]
ok, I was looking on the marketplace page displayed in vsc, would expect the FAQ link there 

https://marketplace.visualstudio.com/items?itemName=rxliuli.joplin-vscode-plugin

**Comment by rxliuli** [comment]
Document added

https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html#how-to-use-plugins-in-two-synchronized-vscode-configurations
