### ISSUE TITLE
[Bug]: Request failed with status code 500

### ISSUE THREAD

**Issue by ytianxia6** [rxliuli/joplin-utils#27]
### 确认事项

- [X] 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### 发生错误的工具/包

joplin-vscode-plugin

### 描述这个错误

`VSCode` 安装 `joplin-vscode-plugins` 插件后，可以看到笔记列表，但尝试打开笔记时报错：

```
command error: joplinNote.openNote{"name":"Error","message":"Request failed with status code 500","stack":"Error: Request failed with status code 500\n\tat createError (c:\\Users\\tianx\\.vscode\\extensions\\rxliuli.joplin-vscode-plugin-0.6.0\\dist\\extension.js:634:15)\n\tat settle (c:\\Users\\tianx\\.vscode\\extensions\\rxliuli.joplin-vscode-plugin-0.6.0\\dist\\extension.js:652:12)\n\tat IncomingMessage.handleStreamEnd (c:\\Users\\tianx\\.vscode\\extensions\\rxliuli.joplin-vscode-plugin-0.6.0\\dist\\extension.js:3124:11)\n\tat IncomingMessage.emit (events.js:327:22)\n\tat endReadableNT (internal/streams/readable.js:1327:12)\n\tat processTicksAndRejections (internal/process/task_queues.js:80:21)"}
```

### 复现错误的步骤

1. 执行`Ctrl+J, Ctrl+J`  
2. 双击一个笔记

### 其他上下文

操作系统： Windows 11
Joplin: 
![image](https://user-images.githubusercontent.com/20197887/147353300-5c841819-071a-4ff2-9a2b-964dacd24d27.png)

VSCode:
![image](https://user-images.githubusercontent.com/20197887/147353402-fd5769c2-0f2a-4422-9281-2daed41de78c.png)

**Comment by rxliuli** [comment]
Can you try the following commands on the command line (please replace token and noteId)

```sh
curl --location --request POST 'http://localhost:27584/services/externalEditWatcher?token=***' \
--header 'Content-Type: application/json' \
--data-raw '{
 "action": "openAndWatch",
 "noteId": "257f6a9dacc1409580ee526d50ac4d49"
}'
```

**Comment by ytianxia6** [comment]
Yes, I tried. but it get the unknow error different with faq
```
PS C:\Users\tianx> curl --location --request POST 'http://localhost:41184/services/externalEditWatcher?token=***' --header 'Content-Type: application/json' --data-raw '{    "action": "openAndWatch",    "noteId": "eef5007790a649c8a939ad5ea0171a3f"}'
{"error":"Internal Server Error: Unexpected token a in JSON at position 5: \n\nSyntaxError: Unexpected token a in JSON at position 5\n    at JSON.parse (<anonymous>)\n    at Api.<anonymous> (C:\\Users\\tianx\\AppData\\Local\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:206:73)\n    at Generator.next (<anonymous>)\n    at C:\\Users\\tianx\\AppData\\Local\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\tianx\\AppData\\Local\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:4:12)\n    at Api.action_services (C:\\Users\\tianx\\AppData\\Local\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:198:16)\n    at Api.<anonymous> (C:\\Users\\tianx\\AppData\\Local\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:155:41)\n    at Generator.next (<anonymous>)\n    at C:\\Users\\tianx\\AppData\\Local\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:8:71"}
```

**Comment by rxliuli** [comment]
Is the web clipper option enabled?

![image](https://user-images.githubusercontent.com/24560368/147353818-7e51d9b8-5a34-493a-9229-d284aae4efbd.png)

**Comment by ytianxia6** [comment]
Yes, it is 
![image](https://user-images.githubusercontent.com/20197887/147353884-c0bd319a-2246-470f-9aba-4d3389409e75.png)

**Comment by rxliuli** [comment]
After enabling this option, check whether it can be accessed normally

```sh
curl http://127.0.0.1:41184/ping
```

![image](https://user-images.githubusercontent.com/24560368/147353885-11c5f93d-ada5-4a58-9309-bd802497798f.png)

**Comment by ytianxia6** [comment]
Yes， it works.
![image](https://user-images.githubusercontent.com/20197887/147354070-6a603398-8650-4c01-a006-444ad8ec88d5.png)

**Comment by rxliuli** [comment]
> "Internal Server Error: Unexpected token a in JSON at position

token needs to be replaced with real

**Comment by ytianxia6** [comment]
yes, i dit it.

![image](https://user-images.githubusercontent.com/20197887/147356473-6de70912-7cf6-4da6-9481-f932ef9ede47.png)

**Comment by rxliuli** [comment]
你可以打开这个网页尝试填写表单提交验证是否可以通过 token 访问 joplin 数据么？

https://joplin-utils.rxliuli.com/web/joplin-batch-web/#/zh-CN/settings

![image](https://user-images.githubusercontent.com/24560368/147356646-26bb9ec4-f67a-42b4-bd6e-a62f4e101a95.png)

**Comment by ytianxia6** [comment]
![image](https://user-images.githubusercontent.com/20197887/147356870-c7e0f3f9-069e-4fdc-ab36-2fb94a6fca7a.png)

是的，可以。
在vscode里，我也是可以看到笔记目录的，只是在尝试打开笔记时才会报错。

**Comment by ytianxia6** [comment]
补充一下，甚至可以在vscode里创建笔记。只是新创建的笔记也不能打开

**Comment by rxliuli** [comment]
> 补充一下，甚至可以在 vscode 里创建笔记。只是新创建的笔记也不能打开

稍晚一点吾辈写一个网页用来帮忙验证 joplin 的这个 api，action api 非常特殊，官方文档没有记录，基本上是为了 vscode 插件作者额外追加的 api，参考：https://discourse.joplinapp.org/t/hope-that-the-web-api-adds-the-following-features-to-support-the-development-of-third-party-extensions/9277

**Comment by rxliuli** [comment]
已添加测试网页，你可以再次尝试一下么？

![image](https://user-images.githubusercontent.com/24560368/147359859-d319e962-fee0-49b7-8460-fae657070a8b.png)

https://joplin-utils.rxliuli.com/web/joplin-batch-web/#/zh-CN/checkActionApi

**Comment by ytianxia6** [comment]
![image](https://user-images.githubusercontent.com/20197887/147360823-e1011f48-256b-491f-9e1c-eabd6753ea42.png)
会提示打开某个笔记，但有没有打开成功好像看不到。 在Joplin里当前笔记并未变化

**Comment by rxliuli** [comment]
> ![image](https://user-images.githubusercontent.com/20197887/147360823-e1011f48-256b-491f-9e1c-eabd6753ea42.png) 会提示打开某个笔记，但有没有打开成功好像看不到。 在 Joplin 里当前笔记并未变化

控制台有什么错误么？

**Comment by ytianxia6** [comment]
![image](https://user-images.githubusercontent.com/20197887/147453882-a9f3c148-185f-4175-be52-841fb9b16c50.png)
控制台错误

**Comment by ytianxia6** [comment]
两个错误分别展开：
![image](https://user-images.githubusercontent.com/20197887/147454129-03b6c02c-cf78-4d35-bede-50b42d3e9114.png)
![image](https://user-images.githubusercontent.com/20197887/147454167-2919578d-6f8b-4225-b31c-f14fa8baccaa.png)

**Comment by rxliuli** [comment]
我在 joplin 官方项目创建了一个问题，你可能还必须在那个问题中提交你的 joplin 日志，issue 链接：https://github.com/laurent22/joplin/issues/5921，调试方法参考：https://joplinapp.org/debugging/

**Comment by ytianxia6** [comment]
按照官方的回复，我发现我的Joplin文本编辑器命令参数是 `-n` ，我把它清空，再次执行上面的工具，joplin会找到默认的markdown 编辑器打开一个文件，在我这里是 `marktext`。

我把Joplin文本编辑器设为 `code.exe`, 插件可以正常使用了。

很奇怪，我没有在工具的任何帮助里找到需要修改 Joplin 编辑器命令的地方。

**Comment by rxliuli** [comment]
抱歉，其实之前也有人遇到过这个问题，吾辈应该写进 faq 中的。。。稍后吾辈将更新文档补充此问题

yhl ***@***.***> 于 2021年12月30日周四 上午9:31写道：

**Comment by rxliuli** [comment]
> 按照官方的回复，我发现我的 Joplin 文本编辑器命令参数是 `-n` ，我把它清空，再次执行上面的工具，joplin 会找到默认的 markdown 编辑器打开一个文件，在我这里是 `marktext`。
> 
> 我把 Joplin 文本编辑器设为 `code.exe`, 插件可以正常使用了。
> 
> 很奇怪，我没有在工具的任何帮助里找到需要修改 Joplin 编辑器命令的地方。

吾辈更新了 faq，如果有任何问题，请告诉吾辈

https://joplin-utils.rxliuli.com/zh/joplin-vscode-plugin/guide/faq.html#%E5%9C%A8%E4%BE%A7%E8%BE%B9%E6%A0%8F%E4%B8%AD%E7%82%B9%E5%87%BB%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80%E7%AC%94%E8%AE%B0
