### ISSUE TITLE
[docs] Setting up extension to work with Joplin as a Flatpak package

### ISSUE THREAD

**Issue by AmrEldib** [rxliuli/joplin-utils#28]
Just wanted to document this solution to a problem I ran into. Please add it to the documentation or FAQ if it's interesting.  

On Linux, Joplin is available as a Flatpak package. When setting up the joplin-vscode-plugin with Joplin installed as a flatpak package, it will fail with a 500 error because of flatpak sandbox restrictions.  

The solution is to set up Joplin to work correctly with VS Code as an external editor. Here's [forum discussion on Joplin flatpak and external editors](https://discourse.joplinapp.org/t/launch-external-editor-linux-ubuntu-popos-flatpak/16118/2).
Go to Joplin > Options > General, and use the following parameters:
Path: `/bin/flatpak-spawn`
Arguments: `--host /usr/bin/code --wait`
I hope this is helpful. Thanks for a useful extension!

**Comment by rxliuli** [comment]
An important change is currently being implemented, and in the future, access to notes and resources will be completely through the data api, no longer relying on the limitation of opening external editors in joplin itself, please use this post to track a change that requires joplin itself: https://discourse.joplinapp.org/t/feat-can-resource-api-support-put-function/24690

**Comment by rxliuli** [comment]
The latest version 0.7.2 should no longer rely on joplin to set up an external editor, can you help verify this?

https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.7.2
