### ISSUE TITLE
[Feat]: 是否可以有一个自动发布博客的方案？Is there any solution to auto pub the blog?

### ISSUE THREAD

**Issue by ytianxia6** [rxliuli/joplin-utils#29]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-blog

### 您的功能请求是否与问题有关？请描述。

我想要一个自动发布博客的方案。

### 描述您想要的解决方案

我还没有开始使用这个插件，我想了解一下，现在有没有一个方案可以把插件布署到一个服务器中，比如docker，当joplin更新笔记后，自动地在服务中更新、打包并发布到静态网站。

### 描述您考虑过的替代方案

将 joplin、插件安装到docker中，并定时更新笔记，如果有更新，就执行编译、发布！

### 其他上下文

我会在多台设备上进行工作，如果每台设备都配置发布环境，太繁琐了。这个活动最好可以自动进行！

_No response_

**Comment by rxliuli** [comment]
这是可能的，在 docker 中安装 joplin-cli 并配置同步，然后安装 joplin-blog，再跑个定时任务就 ok 了（主要是我不确定 joplin 同步是否有任何通知或事件）

**Comment by ytianxia6** [comment]
也就是说，现在没有成熟的方案，必须自己来做是吧。

明白了。等有空的时候试试。

**Comment by rxliuli** [comment]
> 也就是说，现在没有成熟的方案，必须自己来做是吧。
> 
> 明白了。等有空的时候试试。

如果需要，你可以试试 `/events` 相关的 API，它可以拿到最近修改的最多 1000 条历史记录，或许可以用来对比是否修改，不过吾辈没有真正尝试过。
https://joplinapp.org/api/references/rest_api/#events

**Comment by rxliuli** [comment]
另外，建议使用 github 同步发布的项目，以便在多台计算机上使用，参考：https://github.com/rxliuli/blog

**Comment by ytianxia6** [comment]
很奇怪，我使用`npm install -g joplin ` 在docker中安装joplin，总是提示
` npm ERR! git@github.com: Permission denied (publickey).`

**Comment by rxliuli** [comment]
> 很奇怪，我使用 `npm install -g joplin ` 在 docker 中安装 joplin，总是提示 ` npm ERR! git@github.com: Permission denied (publickey).`

吾辈没有这样尝试过，但也许你可以去 Google 看看，可能已经有人遇到过这种问题了。

**Comment by ytianxia6** [comment]
我在布署过程中，遇到一些问题，当我将 blog 标记改为 `posts` 时，日志里有些错误：
![image](https://user-images.githubusercontent.com/20197887/149728955-e66fba16-e346-44b3-92d0-f3953643672a.png)

当我用`blog`时没有问题。我blog标记的日记只有一篇，`posts` 有31篇

**Comment by rxliuli** [comment]
> 我在布署过程中，遇到一些问题，当我将 blog 标记改为 `posts` 时，日志里有些错误： ![image](https://user-images.githubusercontent.com/20197887/149728955-e66fba16-e346-44b3-92d0-f3953643672a.png)
> 
> 当我用 `blog` 时没有问题。我 blog 标记的日记只有一篇，`posts` 有 31 篇

看起来只是一些日志打印，上面那些如果是错误的话指的是获取笔记的标签与资源时未能正确获取到，请检查是否包含这些附件资源

**Comment by ytianxia6** [comment]
也许不是错误，只是太慢了。。
我部署在一台 群晖nas上，最后成功的生成了。但这个过程，很慢。。

**Comment by ytianxia6** [comment]
目前来看，我已经成功实现这个过程。只考虑自用，已经成功部署在我的群晖上。多谢指点。
https://github.com/ytianxia6/joplin-auto-pub
