### ISSUE TITLE
Add ability to specifiy IP/hostname of Joplin API Server

### ISSUE THREAD

**Issue by crosbyh** [rxliuli/joplin-utils#3]
**Is your feature request related to a problem? Please describe.**
By default, Joplin only exposes the API server on localhost/127.0.0.1, and this plugin rightly assumes that is where it is running. I have a different use case: I'm using socat to forward the Joplin API port (from an always-on server) to a network-accessible IP address. I would like to use this plugin, from a different host than my Joplin API server, to connect to my Joplin API server to serve as a Joplin webui behind a reverse proxy.

**Describe the solution you'd like**
I believe that adding the ability to specify an IP address/hostname for the Joplin API server in addition to the port in plugin config would meet this need.

**Describe alternatives you've considered**
I cannot think of another way to achieve this with this plugin. Given the current state of Joplin web interface initiatives, I think that your plugin + some additional VS Code plugins in the style of [Foam](https://foambubble.github.io/foam/) may be a good path toward a usable Joplin web interface.

**Additional context**
The [Node-Red Joplin node palette](https://github.com/ravenscroftj/node-red-contrib-joplin) allows specification of the IP & port for Joplin API server and works well with my Joplin + socat setup currently.

Thanks for your work creating this plugin!

**Comment by rxliuli** [comment]
Someone mentioned this [issue](https://github.com/rxliuli/joplin-vscode-plugin/issues/39) before, but I want to wait for [joplin server](https://discourse.joplinapp.org/ t/joplin-server-pre-release-is-now-available/13605/4) Look at the situation after stabilization

**Comment by crosbyh** [comment]
Sounds good! I’m currently syncing my notes with Joplin Server v2, which came out a couple of weeks ago, and I would be happy to help test this if you decide to implement the feature.

**Comment by rxliuli** [comment]
Try 0.7.2!

https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.7.2
