### ISSUE TITLE
使用当前的 vscode 打开笔记

### ISSUE THREAD

**Issue by Stivenke** [rxliuli/joplin-utils#30]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-vscode-plugin

### 您的功能请求是否与问题有关？请描述。

目前的插件点击笔记后，会打开新的 vscode 实例。
由于我按 [portable](https://portableapps.com/development/portableapps.com_format) 规范将 vscode 整合成便携版本，不能同时运行两个实例，以避免配置冲突。
所以希望该插件能够在“当前的 vscode 中打开笔记”。

### 描述您想要的解决方案

在“当前的 vscode 中打开笔记”。

### 描述您考虑过的替代方案

使用其他的 markdown 外部编辑器，但是明显不方便。

**Comment by rxliuli** [comment]
您是否有办法从命令行通过当前的 vscode 打开笔记，如果有，那么应该是配置 joplin 外部编辑器设置即可。

![image](https://user-images.githubusercontent.com/24560368/149446223-f047d9fe-1326-41fd-aae7-20beb766d5e5.png)
