### ISSUE TITLE
[Bug]: 图片无法导出

### ISSUE THREAD

**Issue by muye06** [rxliuli/joplin-utils#31]
### 确认事项

- [X] 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### 发生错误的工具/包

joplin-blog

### 描述这个错误

win11上试了一下joplin-blog,发现图片无法导出，具体报错如下：

![图片](https://user-images.githubusercontent.com/97824222/149652510-45361e03-07fa-464a-8724-80e6aabafb2b.png)

### 复现错误的步骤

yarn gen后，出现错误，无图笔记全部正常，有图片的报错

### 其他上下文

joplin0.7
nodejs16.13.2
win11

**Comment by rxliuli** [comment]
吾辈怀疑是数据库的错误，之前也有人遇到过，参考：https://github.com/rxliuli/joplin-utils/issues/19

请使用该页面批量检查并修复：https://joplin-utils.rxliuli.com/web/joplin-batch-web/#/fixFileExtension

**Comment by rxliuli** [comment]
暂时不关闭该问题以让吾辈后面记得在 joplin-blog 复制资源时找不到扩展名添加更明确的错误提示

**Comment by muye06** [comment]
你好，非常感谢你的帮助。用了页面修复后，resource文件夹内可以看到图片复制过来了，但是在网页上还无法显示，如下图：
![图片](https://user-images.githubusercontent.com/97824222/149653791-45498785-e8dd-4b6a-b7d3-2e14fb3c81e8.png)
右键新标签页打开后是这样
![图片](https://user-images.githubusercontent.com/97824222/149653746-e8ae53b7-0614-4c57-a02f-e27bd7d4f202.png)

**Comment by rxliuli** [comment]
请配置 hexo 的 `permalink: /p/:abbrlink/`，参考：https://github.com/rxliuli/joplin-utils/blob/ea3f9b541dfff4fa286bbf48183d253ff5d5c162/examples/blog-hexo-example/_config.yml#L18

**Comment by muye06** [comment]
用了你的blog-hexo-example/_config.yml，或配置成permalink: /p/:abbrlink/后，还无法显示
![图片](https://user-images.githubusercontent.com/97824222/149654026-4f98f5a2-f9dc-42d5-9ad1-5263bbc13c27.png)
![图片](https://user-images.githubusercontent.com/97824222/149654077-ba93345c-b889-4f85-ab82-1458e6b54b53.png)
source文件夹如下：
![图片](https://user-images.githubusercontent.com/97824222/149654089-f74b2846-548f-4166-9a1e-41ab9988b8ab.png)
第一次用hexo，不懂555，太麻烦你了

**Comment by rxliuli** [comment]
如果第一次使用的话，可以参考这里，直接使用现有的模板

https://joplin-utils.rxliuli.com/zh/joplin-blog/guide.html#%E5%89%8D%E7%BD%AE%E6%9D%A1%E4%BB%B6

**Comment by rxliuli** [comment]
另外上面的错误看起来是没有正确转换 joplin 的链接为 hexo blog 的链接，可以看下导出的 markdown 中的链接么？是 `/resources/` 开头还是 `:/` 开头

**Comment by muye06** [comment]
![图片](https://user-images.githubusercontent.com/97824222/149654387-ea3245bb-dc88-419a-8388-790aba831cc2.png)
:/开头的

**Comment by muye06** [comment]
也没有拓展名

**Comment by muye06** [comment]
把路径换成/resource/，扩展名加上后，可以正常显示了.....

**Comment by rxliuli** [comment]
能使用该示例测试一下么？

[blog-hexo-example.zip](https://github.com/rxliuli/joplin-utils/files/7876655/blog-hexo-example.zip)

**Comment by rxliuli** [comment]
> 另外上面的错误看起来是没有正确转换 joplin 的链接为 hexo blog 的链接，可以看下导出的 markdown 中的链接么？是 `/resources/` 开头还是 `:/` 开头

等等，你的 joplin 笔记里直接使用 img 标签插入图片？

**Comment by muye06** [comment]
这个笔记是以前印象笔记普通的，不是用markdown语法的

**Comment by rxliuli** [comment]
> 这个笔记是以前印象笔记普通的，不是用 markdown 语法的

那就 gg 了，joplin 官方看起来没有将 en 中的 html 转换为 markdown，吾辈也只处理 markdown 而已。。。如果没有多少的话可以在 joplin 中手动转换过来么？仅转换需要发布为 blog 的部分即可。

**Comment by muye06** [comment]
哦哦，这样呀，找到问题就好，非常感谢你专门帮助我，昨天晚上在你博客看了一阵，joplin+blog这个创意很棒！日后项目如有其他需要，也希望可以帮上忙（虽然我不是程序员，编程只接触过一点）。

**Comment by k3nryu** [comment]
我写了个脚本
1. 可以提取Joplin-Desktop中的附加文件（例如*.png|*.txt|*pdf...etc）放在hexo/source/resources/里面。
2. 自动把Markdown文件中的\[fileName.ext\](:/guid)转换为为\[fileName.ext\](/resources/guid.ext)
如果你跟我一样Hexo在别的机器上的话，需要跟我一样开启sshd，并设置好authorized_keys无密码使用scp
可以参考我的脚步：
```bash
#! /usr/bin/bash

# Get hexo server directory.
hexo_dir=`pwd`
mkdir -p $hexo_dir/tmp $hexo_dir/source/resources

# hexo post resources directory.
local_rsc_dir=$hexo_dir/source/resources/

# Get Joplin-Desktop resources directory.
echo "Where is your Joplin-Desktop resources directory? (mac or win)"
read client
case $client in
        mac)
                remote_rsc_dir=yourName@yourIP:/Users/yourName/.config/joplin-desktop/resources/
                ;;
        win)
                remote_rsc_dir=yourName@yourIP:/C:/User/yourName/.config/joplin-desktop/resources/
                ;;
        *)
                echo "error"
                ;;
esac

echo "What is the new post file path?"
read post_path

while read LINE
do
    if [[ $LINE =~ \!?\[.*\.[0-9a-zA-Z]*\]\(:\/.*\) ]];
    then
        post_rsc_name=`echo $LINE | egrep -o ':/\w*' | cut -c3-`
        ext=`echo $LINE | egrep  -o '\.\w*\]' | sed -e 's/.$//'`
        echo $LINE | sed -e 's/](:/](\/resources/g' -e 's/\s*$//' -e "s/)$/$ext)/g"
        scp $remote_rsc_dir$post_rsc_name$ext $local_rsc_dir > /dev/null
    else
        echo $LINE
    fi
done < ${post_path} > /tmp/tmp.md
\cp -f /tmp/tmp.md $post_path

# 匹配md文件里的添加文件部分
#egrep -o '\!?\[.*\.\w*\]\(:\/.*\)' test.md
# 匹配md文件里的添加文件部分                把':'改为'/resources'
#egrep -o '\!?\[.*\.\w*\]\(:\/.*\)' test.md | sed -e 's/\:/\/resources/'
# 匹配md文件里的添加文件部分                把':'改为'/resources' 把最后面的)删除了
#egrep -o '\!?\[.*\.\w*\]\(:\/.*\)' test.md | sed -e 's/\:/\/resources/;s/)$//'
# 匹配md文件里的添加文件部分                把':'改为'/resources'     提取.txt]文件后缀    删
除文件后缀]
#egrep -o '\!?\[.*\.\w*\]\(:\/.*\)' test.md | sed -e 's/\:/\/resources/' | egrep -o '\.\w*\]' | sed -e 's/\]//g'
~

```

如果觉得不错可以来我GitHub页面给我点个🌟哈
