### ISSUE TITLE
[Feat]: 为什么标签页名字显示的是笔记ID，可读性很差

### ISSUE THREAD

**Issue by admccc** [rxliuli/joplin-utils#32]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-vscode-plugin

### 您的功能请求是否与问题有关？请描述。

![image](https://user-images.githubusercontent.com/12841487/152626280-33acecc7-567d-4a45-a648-318c5fdb987e.png)

### 描述您想要的解决方案

可以替换成笔记标题吗

### 描述您考虑过的替代方案

无

**Comment by rxliuli** [comment]
目前，这是不可能的，因为 vscode 不支持自定义标签页 label。
