### ISSUE TITLE
[Feat]: Force notes to be opened in VSCode

### ISSUE THREAD

**Issue by jerrylususu** [rxliuli/joplin-utils#33]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

My primary markdown editor is Typora, so by default when I double click a markdown file it will be opened in Typora. However, when I'm using the joplin-vscode-plugin, I noticed that if I double click to open a note, it will be opened in Typora but not in VSCode.

### Describe the solution you'd like

I would like to add a setting in the plugin that forces notes to be opened in VSCode. (As I am already using the VSCode plugin, I would probably want to edit my notes in VSCode.)

### Describe alternatives you've considered

I could change the file association so VSCode will be come the default editor for Joplin. But that would break some other workflows that I rely on. 

### Additional context

This happens on Windows 11. I mostly just use the main Joplin program, and only uses VSCode if I need to compare / cross-edit multiple notes.

**Comment by rxliuli** [comment]
faq ref: https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html#show-error-message-joplin-s-token-port-is-set-incorrectly-unable-to-access-joplin-service
