### ISSUE TITLE
[Bug]: unwanted autoplacement

### ISSUE THREAD

**Issue by atao60** [rxliuli/joplin-utils#34]
Ubuntu 20.04
VSC 1.65.2
joplin-vsc-code 0.6.0
joplin 1.7.11 (prod, linux)

Each occurrence of ".properties" or "resources" is replaced by an empty string when I save a document.

I don't know what I'm doing wrong. Is it a setting issue or a bug?
I have no clue where to look for.
May be it's not the right place to ask but any help will be appreciated.

**Comment by rxliuli** [comment]
Please try disabling all plugins except joplin-vscode-plugin to see if it's a problem with the joplin plugin itself, and if you can add a gif or mp4 demo video of the error.
