### ISSUE TITLE
[Feat]: Publish on open-vsx

### ISSUE THREAD

**Issue by marph91** [rxliuli/joplin-utils#38]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

Hi, at first thanks for your work in this repo! I'm using vscodium and wanted to install the Joplin plugin via extension manager. However, it's not available.

### Describe the solution you'd like

This is because the Joplin plugin isn't released on open-vsx.org. It would be very convenient to have it available in the extension manager. Would you consider to publish it as described in https://github.com/eclipse/openvsx/wiki/Publishing-Extensions?

### Describe alternatives you've considered

I know it's probably much work for only one user. It might be sufficient for me to install the plugin manually. ~Could you share where i could get the `.vsix` file?~

**Edit**: The `.vsix` file is available for example at https://marketplace.visualstudio.com/items?itemName=rxliuli.joplin-vscode-plugin -> Download Extension

**Comment by rxliuli** [comment]
There are no plans at the moment, but you do have the ability to self-publish and maintain open.vsx extensions, just like joplin desktop in community-maintained versions of various package managers

**Comment by marph91** [comment]
Alright. For now, the manual import works. If there are more people interested, I would try to self-publish it.
