### ISSUE TITLE
Can not run joplin-batch-web with local http server

### ISSUE THREAD

**Issue by sulisu** [rxliuli/joplin-utils#4]
- [X] I checked [FAQ](https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/faq)

**Describe the bug**

When open the http://127.0.0.1/index.html，chrome returns a blank page with warning in console: 

>Failed to load module script: The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

**To Reproduce**

1. unzip the repo downloaded from github, and make the joplin-batch-web directory as http server root
2. open http://127.0.0.1/index.html with chrome

**Expected behavior**
Should open the joplin-batch-web page

**Screenshots**

**Desktop (please complete the following information):**

- OS: win10
-joplin-batch-web version : master

**Additional context**

**Comment by rxliuli** [comment]
url
https://joplin-utils.rxliuli.com/joplin-batch-web/

**Comment by rxliuli** [comment]
Later I will add the documentation for using the local development environment

**Comment by rxliuli** [comment]
Locally developed documentation has been added
https://github.com/rxliuli/joplin-utils/blob/master/apps/joplin-batch-web/docs/dev.md
