### ISSUE TITLE
[Bug]: 在VScode新版上无法安装

### ISSUE THREAD

**Issue by quancs** [rxliuli/joplin-utils#40]
### 确认事项

- [X] 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### 发生错误的工具/包

joplin-vscode-plugin

### 描述这个错误

安装报错：

`Unable to install because, the extension 'rxliuli.joplin-vscode-plugin' compatible with current version '1.32.3' of VS Code is not found.`

### 复现错误的步骤

vscode中安装joplin-vscode-plugin

**Comment by rxliuli** [comment]
你的 vscode 的版本号是？

**Comment by quancs** [comment]
有点懵，又可以了...好像我有两个版本的vscode（一个1.32.3），一个1.66，刚刚试了下新版1.66是可以的...
