### ISSUE TITLE
[Bug]: I cant open notes 

### ISSUE THREAD

**Issue by gerroon** [rxliuli/joplin-utils#41]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

When I click on a note and try to open with double click this is what I get

```
command error: joplinNote.openNote{"name":"Error","message":"Request failed with status code 404","stack":"Error: Request failed with status code 404\n    at createError (c:\apps\\VSCODE\\.vscode-oss\\node_modules\\.pnpm\\axios@0.21.4\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (c:\apps\\VSCODE\\.vscode-oss\\node_modules\\.pnpm\\axios@0.21.4\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (c:\apps\\VSCODE\\.vscode-oss\\node_modules\\.pnpm\\axios@0.21.4\\node_modules\\axios\\lib\\adapters\\http.js:269:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}
```

I am using Vscodium 1.65 and Joplin extension 0.6 on Windows, against Joplin Cli

### Steps to reproduce the behavior

I cant read this stuff

### Additional context

I cant read this stuff

**Comment by rxliuli** [comment]
Have you tried the latest version of the vscode plugin? You will need to install manually from vscode, it is currently in beta

https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.7.1

**Comment by gerroon** [comment]
It says it is not compatiple with Vs Code 1.65

**Comment by rxliuli** [comment]
> It says it is not compatiple with Vs Code 1.65

Yes it uses the latest version of vscode 1.66.2, I used some newer vscode extension api so upgraded it to the latest version today

**Comment by gerroon** [comment]
Never mind, upgraded VsCodium and installed the extension manually now I am able to load the notes. Thanks for the extension
