### ISSUE TITLE
[Bug]: 请问打不开md里的链接是bug吗

### ISSUE THREAD

**Issue by guba-exe** [rxliuli/joplin-utils#42]
### 确认事项

- [X] 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### 发生错误的工具/包

joplin-vscode-plugin

### 描述这个错误

在vscode的预览里想用链接在joplin笔记间跳转，提示无法打开:/xxxxx 没有找到文件，请问这是一个bug吗? 我该如何解决它?

### 复现错误的步骤

1. 使用joplin-复制markdown地址添加一个链接
2. 在vscode中试着打开这个链接

**Comment by rxliuli** [comment]
是否可以在浏览器输入以下链接打开笔记？（请替换成你的笔记 id）

vscode://rxliuli.joplin-vscode-plugin/open?id=9751355186fd4c5bbad0d041fe85c256

**Comment by guba-exe** [comment]
确认过，可以打开

**Comment by rxliuli** [comment]
使用最新版本看看
https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.7.4

**Comment by rxliuli** [comment]
该版本依赖于最新的 joplin 与 vscode

Joplin 版本 > v2.8
VSCode 版本 > v1.66.2

**Comment by guba-exe** [comment]
在预览中点击链接依然无效，但是在编辑区按住ctrl+点击是有效的。在回退插件版本到0.6.0后发现原来的编辑区中跳转也是有效的，这是否是Markdown预览的问题 ?

**Comment by rxliuli** [comment]
有可能，可以打开 webview 开发者工具看一下链接是什么么？
![image](https://user-images.githubusercontent.com/24560368/165040642-99d914ad-3df8-4549-901b-8b024f1e0344.png)
![image](https://user-images.githubusercontent.com/24560368/165040701-1fb04758-cbde-4ed1-8a9b-f750b207481d.png)

**Comment by guba-exe** [comment]
经过测试，Markdown Preview Enhanced 的预览中会出现这样的问题，它的a元素如下。
```html
<a href="https://file+.vscode-resource.vscode-webview.net/c:/Users/17458/AppData/Roaming/Code/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/:/567118defb0e419e84fd5e9b2e8124cb">命令</a>
```
如果使用Markdown自带插件，那么预览中链接可以正常使用，它的a元素作为对比如下
```html
<a href="vscode://rxliuli.joplin-vscode-plugin/open?id%3D567118defb0e419e84fd5e9b2e8124cb" data-href="vscode://rxliuli.joplin-vscode-plugin/open?id%3D567118defb0e419e84fd5e9b2e8124cb" title="vscode://rxliuli.joplin-vscode-plugin/open?id%3D567118defb0e419e84fd5e9b2e8124cb">命令</a>
```

**Comment by rxliuli** [comment]
> 经过测试，Markdown Preview Enhanced 的预览中会出现这样的问题，它的 a 元素如下。
> 
> ```
> <a href="https://file+.vscode-resource.vscode-webview.net/c:/Users/17458/AppData/Roaming/Code/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/:/567118defb0e419e84fd5e9b2e8124cb">命令</a>
> ```
> 
> 如果使用 Markdown 自带插件，那么预览中链接可以正常使用，它的 a 元素作为对比如下
> 
> ```
> <a href="vscode://rxliuli.joplin-vscode-plugin/open?id%3D567118defb0e419e84fd5e9b2e8124cb" data-href="vscode://rxliuli.joplin-vscode-plugin/open?id%3D567118defb0e419e84fd5e9b2e8124cb" title="vscode://rxliuli.joplin-vscode-plugin/open?id%3D567118defb0e419e84fd5e9b2e8124cb">命令</a>
> ```

可能是那个插件也会修改 markdown 渲染器，建议使用 [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)，参考：https://joplin-utils.rxliuli.com/zh/joplin-vscode-plugin/guide/recommended-extension.html

**Comment by rxliuli** [comment]
补充技术细节（冲突的 api）：
https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-support-for-new-syntax-with-markdownit-plugins
