### ISSUE TITLE
[Bug]: 图片显示

### ISSUE THREAD

**Issue by guba-exe** [rxliuli/joplin-utils#43]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

无法显示joplin中的图片

### Steps to reproduce the behavior

1. 在joplin中上传图片，样式如![dc9abd89e7a7f6f6cc8f88eb100feb8d.png](:/80482c933cfc4a7187cb001a780c1ad9)
2. 在VScode中使用Joplin插件打开包含图片的文档
3. 图片没有显示

### Additional context

值得注意的是 如果使用joplin自带的切换外部编辑，图片是可以显示的

**Comment by rxliuli** [comment]
请允许本地 http 资源
![image](https://user-images.githubusercontent.com/24560368/165308059-9c5faa1f-9895-4c33-8aa9-71734efa6f2c.png)

**Comment by guba-exe** [comment]
感谢解答

**Comment by onewesong** [comment]
所以 img标签什么时候可以支持呢，大佬

**Comment by rxliuli** [comment]
> 所以 img 标签什么时候可以支持呢，大佬

晚点吧
