### ISSUE TITLE
[Bug]: 插件错误地将一级标题处理为笔记名

### ISSUE THREAD

**Issue by guba-exe** [rxliuli/joplin-utils#44]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

如果文档的第一行是# 1 一级标题，处理时会被当做标题处理，如果对文件做了任何修改而保存，文档的名字会被修改为第一个一级标题的名称。

### Steps to reproduce the behavior

1. 在joplin下有文档的第一行是#1一级标题
2. 使用VSCode打开
3. 做出任何改动后保存
4. 文档的标题被错误地改变

### log file

没有找到打开log的命令，这个BUG复现较容易，应该不会碍事

**Comment by rxliuli** [comment]
这不是一个 bug，是为了与 joplin 使用外部编辑器的行为保持一致
