### ISSUE TITLE
[Bug]: joplin-blog 无法运行

### ISSUE THREAD

**Issue by Taurus-ZSZ** [rxliuli/joplin-utils#45]
### 确认事项

- [X] 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### 发生错误的工具/包

joplin-blog

### 描述这个错误

当我尝试运行你的example  yarn gen 命令 时出现下面的错误
my_blog/node_modules/.bin/joplin-blog:行1: 未预期的符号“'./dist/cjs/bin.js'”附近有语法错误
my_blog/node_modules/.bin/joplin-blog:行1: `require('./dist/cjs/bin.js')

### 复现错误的步骤

1. 使用 vscode 打开 .joplin-blog.json 配置文件
2. 修改 joplinProfilePath/token/port 三个配置
3. 删除 source/_posts 目录
4. 为一些笔记添加 blog 标签
5. 运行 yarn gen 从 joplin 读取 blog 标签的笔记并写入到当前目录
执行到第5步时出现错误

### 日志文件

[waves@waves-pc blog-hexo-example]$ yarn gen
yarn run v1.22.18
$ joplin-blog blog
/home/waves/Downloads/joplin_blog/blog-hexo-example/node_modules/.bin/joplin-blog:行1: 未预期的符号“'./dist/cjs/bin.js'”附近有语法错误
'home/waves/Downloads/joplin_blog/blog-hexo-example/node_modules/.bin/joplin-blog:行1: `require('./dist/cjs/bin.js')
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 其他上下文

joplin-blogv0.82
yarn run v1.22.18

**Comment by rxliuli** [comment]
[joplin-blog 0.8.1](https://github.com/rxliuli/joplin-utils/releases/tag/joplin-blog%400.8.1) 之后不再使用 joplinProfilePath 和 port 配置，但需要添加新的 baseUrl 配置，参考：
https://joplin-utils.rxliuli.com/zh/joplin-blog/#%E9%85%8D%E7%BD%AE

**Comment by rxliuli** [comment]
啊，你的 nodejs 版本是多少呢？

**Comment by Taurus-ZSZ** [comment]
[waves@waves-pc blog-hexo-example]$ node -v
v18.1.0

**Comment by rxliuli** [comment]
吾辈发布了 0.8.3，你可以再试试么？

**Comment by Taurus-ZSZ** [comment]
我的.joplin-blog.json文件如下：
{
  "type": "hexo",
  "rootPath": ".",
  "baseUrl": "http://localhost:41184",
  "token": "xxxxxxxae9c0e42e042a963be8534",
  "tag": "blog"
}
[waves@waves-pc blog-hexo-example]$ npm -v
8.5.5
 可以试试，但是我用你的那个脚本执行提示的安装版本只显示到0.8.2

**Comment by rxliuli** [comment]
> 我的.joplin-blog.json 文件如下： { "type": "hexo", "rootPath": ".", "baseUrl": "http://localhost:41184", "token": "xxxxxxxae9c0e42e042a963be8534", "tag": "blog" } [waves@waves-pc blog-hexo-example]$ npm -v 8.5.5 可以试试，但是我用你的那个脚本执行提示的安装版本只显示到 0.8.2

修改 package.json 中的 0.8.2 => 0.8.3，然后重新运行 yarn && yarn gen

**Comment by Taurus-ZSZ** [comment]
好的，我修改了版本后之前的错误消失了，但是他提示了新的错误
yarn gen
yarn run v1.22.18
$ joplin-blog blog
/usr/bin/env: "node\r": 没有那个文件或目录
/usr/bin/env: 使用 -[v]S 以在 shebang 行中传递选项
error Command failed with exit code 127.

**Comment by rxliuli** [comment]
先直接运行原始 bin.cjs 吧

```sh
node ./node_modules/joplin-blog/bin.cjs blog
```

**Comment by Taurus-ZSZ** [comment]
运行之后提示的消息，似乎是链接被拒绝了
`[waves@waves-pc blog-hexo-example]$ node ./node_modules/joplin-blog/bin.cjs blog
    _             _ _             _     _             
   (_) ___  _ __ | (_)_ __       | |__ | | ___   __ _ 
   | |/ _ \| '_ \| | | '_ \ _____| '_ \| |/ _ \ / _` |
   | | (_) | |_) | | | | | |_____| |_) | | (_) | (_| |
  _/ |\___/| .__/|_|_|_| |_|     |_.__/|_|\___/ \__, |
 |__/      |_|                                  |___/ 
(node:6295) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Failed to test joplin service:  TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:5575:34)
    at node:internal/deps/undici/undici:5901:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED ::1:41184
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 41184
  }
}
`

**Comment by rxliuli** [comment]
稍等，吾辈装个 docker 用 nodejs 18 + linux 环境跑一下，windows 上 nodejs 16 lts 复现不了

**Comment by Taurus-ZSZ** [comment]
麻烦大神了，我的平台是archlinux 您看您这边需要我提供什么信息吗？
uname -a
Linux waves-pc 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux
[waves@waves-pc blog-hexo-example]$ node -v
v18.1.0
[waves@waves-pc blog-hexo-example]$ npm -v
8.5.5
[waves@waves-pc blog-hexo-example]$ yarn -v
1.22.18
[waves@waves-pc blog-hexo-example]$

**Comment by Taurus-ZSZ** [comment]
有一个信息我不知道有没有用？
我直接在浏览器中访问http://localhost:41184/
他返回的是
[11.pdf](https://github.com/rxliuli/joplin-utils/files/8646476/11.pdf)

**Comment by rxliuli** [comment]
只要访问这个能响应 JoplinClipperServer 就代表服务正常

http://localhost:41184/ping

**Comment by Taurus-ZSZ** [comment]
> 

是的,我测试过了，可以响应这个的。

**Comment by rxliuli** [comment]
发布了 0.8.5，测试在 ubuntu docker image + nodejs v18.1.0 可用，你可以更新再试一次么？

**Comment by Taurus-ZSZ** [comment]
> 发布了 0.8.5，测试在 ubuntu docker image + nodejs v18.1.0 可用，你可以更新再试一次么？

我再次从你的github上下载了你的源码，然后单独拿出你的blog-hexo-example 我执行 yarn && yarn gen 依旧报出下面的错误
我准备换个joplin版本试试
(node:3975) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Failed to test joplin service:  TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:5575:34)
    at node:internal/deps/undici/undici:5901:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED ::1:41184
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 41184
  }
}
Done in 0.60s.

**Comment by rxliuli** [comment]
试试访问以下 url 能否获取到标签为 blog 的笔记列表（替换 token/port 为你的）

```sh
http://localhost:27583/search?fields=id,title,body,user_created_time,user_updated_time&limit=100&page=1&query=tag%3Ablog&token=5bcfa49330788dd68efea27a0a133d2df24df68c3fd78731eaa9914ef34811a34a782233025ed8a651677ec303de6a04e54b57a27d48898ff043fd812d8e0b31&type=note
```

**Comment by Taurus-ZSZ** [comment]
> 
我测试了一下这样是可以获得我的笔记列表的，我截图了放在了pdf里
[Uploading 11.pdf…]()

**Comment by rxliuli** [comment]
> > 
> 
> 我测试了一下这样是可以获得我的笔记列表的，我截图了放在了 pdf 里 Uploading 11.pdf…

没有上传完

**Comment by Taurus-ZSZ** [comment]
> 

[11.pdf](https://github.com/rxliuli/joplin-utils/files/8646777/11.pdf)

**Comment by rxliuli** [comment]
可以确定是这一行抛出的错误，但为什么会抛出错误就很迷惑。。。
https://github.com/rxliuli/joplin-utils/blob/38a657cc619ede76eae2040f365037f971e829af/apps/joplin-blog/src/blog/Application.ts#L96

**Comment by rxliuli** [comment]
可以使用 chrome 远程桌面连接到你的 pc 调试一下么？如果可以请发送 code 至邮箱 rxliuli@gmail.com

使用参考：https://remotedesktop.google.com/support

**Comment by Taurus-ZSZ** [comment]
邮件收到了吗

**Comment by rxliuli** [comment]
没

**Comment by Taurus-ZSZ** [comment]
> 

362167700524

**Comment by Taurus-ZSZ** [comment]
099141653572 刚才电脑死机了

**Comment by rxliuli** [comment]
后续需要解决 nodejs 18 的 fetch 存在兼容问题

**Comment by Taurus-ZSZ** [comment]
> 后续需要解决 nodejs 18 的 fetch 存在兼容问题

谢谢啦，麻烦了你一整天
