### ISSUE TITLE
[Bug]: Can't display images in Markdown Preview Enhanced

### ISSUE THREAD

**Issue by roooooc** [rxliuli/joplin-utils#46]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

Pictures can be displayed normally in **default vscode markdown preview** , 
but can't display in **Markdown Preview Enhanced**

### Steps to reproduce the behavior

open joplin
preiew markdown

### log file

I cant read this stuff

### Additional context

I cant read this stuff

**Comment by rxliuli** [comment]
Need to configure to allow display of local insecure resources, for example if using vscode default previewer is like this

![image](https://user-images.githubusercontent.com/24560368/172980136-f0b11212-9b4d-44dc-a10a-038d0f18c39b.png)

**Comment by rxliuli** [comment]
Tested the plugin, it doesn't use the vscode markdown-it extension option, can't fix
ref: https://code.visualstudio.com/api/extension-guides/markdown-extension
