### ISSUE TITLE
[Bug]: Note name breaking

### ISSUE THREAD

**Issue by ArtyomFR** [rxliuli/joplin-utils#47]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

When using a `#` in first line of note break the note title after saving.

### Steps to reproduce the behavior

1. Create a note in joplin
2. Name it "Good name"
3. Rigth "# Bad name" on the first line of the note
4. Open the note in VSCode
5. Save the note
6. Congratulation, the name of the note break.

### log file

{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote start, id: 1e2d666a0aa24508be600efc055b51b0, title: Bad Name","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote write tempFile: /home/administrateur/.config/Code/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/Bad Name.md","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote open tempFile","pluginVersion":"0.7.9"}
{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote start, id: c7f12ff25eed4942b8116c051aa000c8, title: Good name","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote write tempFile: /home/administrateur/.config/Code/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/Good name.md","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote open tempFile","pluginVersion":"0.7.9"}
{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote start, id: 1e2d666a0aa24508be600efc055b51b0, title: Bad Name","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote write tempFile: /home/administrateur/.config/Code/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/Bad Name.md","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote open tempFile","pluginVersion":"0.7.9"}
{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote start, id: c7f12ff25eed4942b8116c051aa000c8, title: Good name","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote write tempFile: /home/administrateur/.config/Code/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/Good name.md","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote open tempFile","pluginVersion":"0.7.9"}
{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote start, id: 1e2d666a0aa24508be600efc055b51b0, title: Bad Name","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote write tempFile: /home/administrateur/.config/Code/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/Bad Name.md","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote open tempFile","pluginVersion":"0.7.9"}
{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote start, id: c7f12ff25eed4942b8116c051aa000c8, title: Good name","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote write tempFile: /home/administrateur/.config/Code/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/Good name.md","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote open tempFile","pluginVersion":"0.7.9"}
{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"0.7.9"}
{"level":"info","message":"openNote start, id: 1e2d666a0aa24508be600efc055b51b0, title: Bad content","pluginVersion":"0.7.9"}
{"level":"info","message":"command execute: joplinNote.showLogFileDir","pluginVersion":"0.7.9"}

### Additional context

It seems that the plugin display the note name on the first line as "# Title".
If note already contain a "#Content" on the first line, it skip the adding of the true title.
Then, when saving using the "#Content" as title and rename the note with the wronf name.

**Comment by rxliuli** [comment]
Do you mean that changing the first-level title of the note content will cause the note title to change? This is a deliberate feature, not a bug

**Comment by ArtyomFR** [comment]
Joplin desktop app allow to use a note name independent of note content.
When editing the note in external app it append the name on first line without first level title.
Most of my notes have different name than the first level title. Then transitioning to this tools mean a loss of feature from Joplin and process to migrate all notes. That why I dosn't thought it was intentional.
One thing that could resolve this is to actually append the name in first line like Desktop app instead of assuming the first level title is also the note title.

**Comment by rxliuli** [comment]
Also, you don't need to migrate all your existing notes at once, it just automatically updates the title when you modify it, that's all

**Comment by ArtyomFR** [comment]
Sure, but let's take an exemple:
I've a note named "WSUS".
The first line in the note is "# WSUS: Mise à jours des postes utilisateurs"
If I edit the note in external app (vscode) from joplin, no problem.
If I edit the note directly in VSCode with this tool and save it, the name will change from "WSUS" to "#WSUS: Mise à jours des postes utilsateurs" and the first level title will disapear from the note in joplin.

**Comment by ArtyomFR** [comment]
The external app link assume the first line is the name because it append it when oppening the note.
The plugin assume the first line is the name but doesn't append it first when oppening the note.

**Comment by rxliuli** [comment]
> The external app link assume the first line is the name because it append it when oppening the note. The plugin assume the first line is the name but doesn't append it first when oppening the note.

In fact, the plugin does this to mimic joplin's behavior as closely as possible

1. When saving a note, the first-level title will be automatically used as the note title, and the first-level title will be deleted from the note content
2. When opening a note, it concatenates the note title and content and writes it to a temporary file

https://user-images.githubusercontent.com/24560368/175022462-b4e88e92-e921-4144-8ada-56581042d23b.mp4

**Comment by ArtyomFR** [comment]
Good name and content
![image](https://user-images.githubusercontent.com/20092228/175029329-ff371b3c-ec80-4a58-8e7d-32cf18340dba.png)
Opening in vscode, no problem
![image](https://user-images.githubusercontent.com/20092228/175029371-c6e0accd-6d0c-4364-8094-667c0bc65103.png)
Saving, note name change
![image](https://user-images.githubusercontent.com/20092228/175029417-5059d16d-5372-4baf-8a57-2ca689b8cda0.png)
Returning to joplin original title is lost
![image](https://user-images.githubusercontent.com/20092228/175029516-030dd763-aa05-46ae-a97f-de38e3c8cc68.png)

**Comment by rxliuli** [comment]
However, if a markdown file contains two first-level headings it will cause some errors, such as the following markdown content

```md
# WSUS

# WSUS: Mise à jours des postes utilisateurs

test
```

So I did the "smart" processing before, which is really not as expected

**Comment by rxliuli** [comment]
I have released 0.7.10, can you try installing it manually?

https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.7.10

**Comment by ArtyomFR** [comment]
> I have released 0.7.10, can you try installing it manually?
> 
> https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.7.10

It's good! Now the original title is appended to the top of the note, so when saving it use the original title and note the first line of content.
Thank's for the help!
