### ISSUE TITLE
[Bug]: 图片无法显示

### ISSUE THREAD

**Issue by onewesong** [rxliuli/joplin-utils#48]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

joplin内图片可以正常显示
vscode `markdown preview` 和`Office Viewer` 均无法正常显示
p.s. 已设置 markdown.showPreviewSecuritySelector

### Steps to reproduce the behavior

1. 设置markdown.showPreviewSecuritySelector
2. 打开markdown预览

### log file

{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"0.7.10"}
{"level":"info","message":"openNote start, id: e498b6d5f20748a8b75aab82d8f7fe0e, title: Go 语言垃圾收集器的实现原理","pluginVersion":"0.7.10"}
{"level":"info","message":"openNote write tempFile: /Users/songe/Library/Application Support/Code - Insiders/User/globalStorage/rxliuli.joplin-vscode-plugin/.tempNote/Go 语言垃圾收集器的实现原理.md","pluginVersion":"0.7.10"}
{"level":"info","message":"openNote open tempFile","pluginVersion":"0.7.10"}
{"level":"info","message":"command execute: joplinNote.showResources","pluginVersion":"0.7.10"}
{"level":"warn","message":"showResources.noteId: undefined","pluginVersion":"0.7.10"}
{"level":"info","message":"command execute: joplinNote.showResources","pluginVersion":"0.7.10"}
{"level":"warn","message":"showResources.noteId: undefined","pluginVersion":"0.7.10"}
{"level":"info","message":"command execute: joplinNote.showLogFileDir","pluginVersion":"0.7.10"}

### Additional context

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17920822/175332769-dee6ef10-aecb-4108-9f41-e1ebe68c8209.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17920822/175333863-689ac9d4-0976-4a39-9f89-ed0961654118.png">

<img width="881" alt="image" src="https://user-images.githubusercontent.com/17920822/175333355-58988d1d-31f2-47ab-8e95-621a26b81b37.png">

**Comment by onewesong** [comment]
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/17920822/175338887-a7f4cdf6-582c-4886-a991-64bf322961e4.png">
测试了下，是这种的还不支持预览吗

**Comment by onewesong** [comment]
https://github.com/rxliuli/joplin-utils/issues/43

**Comment by rxliuli** [comment]
使用 markdown 语法的是支持的，但不支持 <img> 标签，另外，如果你使用了非官方的 markdown 渲染插件，可能会出现一些问题，例如 Markdown Preview Enhanced
https://joplin-utils.rxliuli.com/zh/joplin-vscode-plugin/guide/faq.html#%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%8F%92%E4%BB%B6-markdown-preview-enhanced

**Comment by onewesong** [comment]
> 使用 markdown 语法的是支持的，但不支持 `<img>` 标签，另外，如果你使用了非官方的 markdown 渲染插件，可能会出现一些问题，例如 Markdown Preview Enhanced https://joplin-utils.rxliuli.com/zh/joplin-vscode-plugin/guide/faq.html#%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%8F%92%E4%BB%B6-markdown-preview-enhanced

可以给个支持的示例吗

**Comment by onewesong** [comment]
好的，我再看看

**Comment by rxliuli** [comment]
已实现，但这让插件的 bundle 尺寸增加了 160kb，可能晚点还需要重构或优化

![image](https://user-images.githubusercontent.com/24560368/175348437-1fcba4d6-a662-4896-a933-ebb45d4b5659.png)

**Comment by rxliuli** [comment]
已发布，请手动安装预览版测试
https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.7.11

**Comment by onewesong** [comment]
🐂niubility！
