### ISSUE TITLE
Remote install joplin-vscode-plugin opens documents in editor on remote server

### ISSUE THREAD

**Issue by deftdawg** [rxliuli/joplin-utils#5]
- [ ] I checked [FAQ](https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/faq) <-- URL is 404

**Describe the bug**

Attempting to open a joplin note from a remote client opens it on the server side instead.

**To Reproduce**

1. Install Joplin on server, copy clipper access token
2. Connect to Server with VSCode "Connect to Host..." over ssh
3. Install Joplin-vscode-plugin, configure "Server" tab with clipper access token
4. Vscode: Reload Window
5. Joplin notes list appears
6. Clicking on a note opens the document on the server -> oops

**Expected behavior**

Clicking the document should open it on client

**Screenshots**

https://user-images.githubusercontent.com/4991612/130132517-080b2b2b-e715-4600-b783-5dcc8baf4f51.mp4

(Download and play in VLC if doesn't show up in browser)

**Desktop (please complete the following information):**

- OS: Windows VSCode + Linux Server
- Joplin platform-version: 2.3.3
- VSCode version: 1.59.0
- joplin-vscode-plugin version: 0.5.2

**Additional context**

This is probably a pretty unusual use case, so I full understand if you don't want to or cannot fix it. 🍻

**Comment by rxliuli** [comment]
duplicate：https://github.com/rxliuli/joplin-utils/issues/3

**Comment by deftdawg** [comment]
Not sure this is related to #3 at all...  Testing locally on the server actually yields the same behaviour.

My best guess is the following line is being executed; however the external editor is set to `gedit` rather than VS Code
```ts
    return this.ajax.post('/services/externalEditWatcher', {
```
(from https://github.com/rxliuli/joplin-utils/blob/master/libs/joplin-api/src/api/NoteActionApi.ts#L33)

Guessing to fix it would take some rewriting though; fetching the note body (using [GET /notes/:id](https://joplinapp.org/api/references/rest_api/#get-notes-id)) and pushing that content into an internal VS code editor.   Plus might want to do periodic checks for changes and check for potential conflict on saves...

**Comment by rxliuli** [comment]
> Not sure this is related to #3 at all... Testing locally on the server actually yields the same behaviour.
> 
> My best guess is the following line is being executed; however the external editor is set to `gedit` rather than VS Code
> 
> ```ts
>     return this.ajax.post('/services/externalEditWatcher', {
> ```
> 
> (from https://github.com/rxliuli/joplin-utils/blob/master/libs/joplin-api/src/api/NoteActionApi.ts#L33)
> 
> Guessing to fix it would take some rewriting though; fetching the note body (using [GET /notes/:id](https://joplinapp.org/api/references/rest_api/#get-notes-id)) and pushing that content into an internal VS code editor. Plus might want to do periodic checks for changes and check for potential conflict on saves...

ref: https://github.com/rxliuli/joplin-vscode-plugin/issues/39

**Comment by deftdawg** [comment]
Read that, it's not the same issue;  VS Code is running over an SSH tunnel... 

Joplin is running on a Linux Laptop; VS Code's front end is running locally on Windows and it's backend is being run on the same Linux machine as Joplin (via Connect to Host... over SSH)

The API is not restricted as the host is localhost:
![image](https://user-images.githubusercontent.com/4991612/130175997-d89e8b33-b006-4745-96bf-0176e57e76f8.png)

A more common manifestation of this problem (with everything on one machine) is if the `.md` file asscociated is not owned by VS Code.   Clicking on the note with the joplin-vscode-plugin will open the other file editor outside of VS Code.

**Comment by rxliuli** [comment]
> A more common manifestation of this problem (with everything on one machine) is if the `.md` file association is not owned by VS Code. Clicking on the note from the joplin-vscode-plugin's list will open the file in an editor outside of VS Code.

https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html#not-opened-in-vscode-after-clicking

**Comment by rxliuli** [comment]
In addition, the faq 404 problem in the template is fixed

**Comment by deftdawg** [comment]
Cheers - yup the Joplin FAQ link in the answer suggests how to external edit, not sure in explicitly mentions the need for the file association, but good enough.

I'm take a go at forking to pull and push the note body over the payload since I kinda want to use it that way... If I get something I'll do a PR

**Comment by deftdawg** [comment]
Not to bad fetching the data and spitting it into an editor(code below), but obviously needs a different approach to mapping the data so that it can be POSTed back when a `save` event fires

Maybe have to look at how [ssh-fs](https://github.com/SchoofsKelvin/vscode-sshfs) extension handles it's files...

```typescript
  async openNote(item: Omit<FolderOrNote, 'item'> & { item: JoplinListNote }) {
    console.log('openNote: ', item.id, await 
      noteApi.get(item.id, [
        'id',
        'parent_id',
        'title',
        'is_todo',
        'todo_completed',
        'body'
      ]).then (
          note => {
            vscode.workspace.openTextDocument( {
              content: note.body,
              language: 'markdown'
            } ).then(
                doc => vscode.window.showTextDocument( doc )
            );
          }
        )
      )
  }
```

**Comment by rxliuli** [comment]
> Not to bad fetching the data and spitting it into an editor(code below), but obviously needs a different approach to mapping the data so that it can be POSTed back when a `save` event fires
> 
> Maybe have to look at how [ssh-fs](https://github.com/SchoofsKelvin/vscode-sshfs) extension handles it's files...
> 
> ```ts
>   async openNote(item: Omit<FolderOrNote, 'item'> & { item: JoplinListNote }) {
>     console.log('openNote: ', item.id, await 
>       noteApi.get(item.id, [
>         'id',
>         'parent_id',
>         'title',
>         'is_todo',
>         'todo_completed',
>         'body'
>       ]).then (
>           note => {
>             vscode.workspace.openTextDocument( {
>               content: note.body,
>               language: 'markdown'
>             } ).then(
>                 doc => vscode.window.showTextDocument( doc )
>             );
>           }
>         )
>       )
>   }
> ```

joplin api provides the function of update note, please refer to: <https://joplin-utils.rxliuli.com/joplin-api/classes/api_NoteApi.NoteApi.html#update>

But it’s not only the notes that need to be considered, but also the attachments in the notes

1. The link of the attachment in the note is </resources/:id>, if you want to display it correctly, you also need to modify the markdown-it rendering part
2. Attachments are not always able to be opened in vscode, so a file monitor must be implemented to automatically update through the api when the opened attachment changes
