### ISSUE TITLE
这个插件不能触发代码自动补全等操作吗

### ISSUE THREAD

**Issue by ccvbc** [rxliuli/joplin-utils#52]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-vscode-plugin

### 您的功能请求是否与问题有关？请描述。

这个本质上还是在joplin中写，vscode只是外部编辑器吗

### 描述您想要的解决方案

简单问问

### 描述您考虑过的替代方案

简单问问

### 其他上下文

简单问一下

**Comment by rxliuli** [comment]
> 这个插件不能触发代码自动补全等操作吗

不清楚你指的自动补全是什么？

> 这个本质上还是在 joplin 中写，vscode 只是外部编辑器吗

不完全是，vscode 现在会自行创建临时文件并监视文件变更，也会将 :/ 的资源链接渲染为正确的 joplin 资源链接。例如你可以插入图片，也可以为笔记附加标签，这都是单纯的外部编辑器做不到的。而这一切全部依赖于 joplin data api，它支持以编程的方式操作 joplin 的数据。
