### ISSUE TITLE
[Feat]: 增加选项控制是否把 note title/name 带到 .md 文件中

### ISSUE THREAD

**Issue by calfzhou** [rxliuli/joplin-utils#53]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

目前 joplin-vscode-plugin 会把 note name 以 H1 添加到 markdown 文件中，而 note 内容中原本就有一个 H1 作为标题，就会出现两个一样的 H1，这也违反了 single h1 的语法规范，在编辑和预览的过程中都比较难受。

<img width="721" alt="image" src="https://user-images.githubusercontent.com/3761553/183033585-fecaa922-74f6-456f-8bda-95aec7a3b3b1.png">

### Describe the solution you'd like

Joplin 里关于 note name 和 the first header in the markdown text 的争论一直没有定论（[Remove superfluous note names - Features - Joplin Forum](https://discourse.joplinapp.org/t/remove-superfluous-note-names/9862)），使用者们也有各自的喜好。

所以是不是可以增加一个选项，用户根据自己的使用习惯来决定是把 note name 添加为 H1 还是直接忽略掉它。

### Describe alternatives you've considered

N/A

**Comment by rxliuli** [comment]
试试删除掉下面那个，保存，然后重新打开，它应该只有一个标题了

**Comment by rxliuli** [comment]
> the first header in the markdown text

插件使用这个

**Comment by calfzhou** [comment]
> 试试删除掉下面那个，保存，然后重新打开，它应该只有一个标题了

删掉一个，保存之后，去 Joplin 客户端里看，note 内容里的 H1 就被删掉了。

**Comment by rxliuli** [comment]
> > 试试删除掉下面那个，保存，然后重新打开，它应该只有一个标题了
> 
> 删掉一个，保存之后，去 Joplin 客户端里看，note 内容里的 H1 就被删掉了。

是的，实际上会在保存时自动提取标题和内容写入到 joplin，这是预期的行为。如果只使用插件，甚至不会注意到这一点。
