### ISSUE TITLE
[Feat]: Deploy joplin-util at https://open-vsx.org/

### ISSUE THREAD

**Issue by trixam** [rxliuli/joplin-utils#54]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

Allow Codium users to participate in Joplin-Util without manual installation.

### Describe the solution you'd like

Release of Joblin-Util on https://open-vsx.org/

### Describe alternatives you've considered

...

### Additional context

Thank you for Joblin-Util. Rarely has a plugin inspired me so much! Keep it up.

**Comment by marph91** [comment]
Hi @trixam, I had the same idea at https://github.com/rxliuli/joplin-utils/issues/38. The current state is that one would have to self-publish on https://open-vsx.org.

**Comment by trixam** [comment]
Hi @marph91. That doesn't make sense for me. There is a  [github action](https://github.com/HaaLeo/publish-vscode-extension#readme) that will do the job automatically for open-vsx also vscode marketplace.

**Comment by rxliuli** [comment]
> Hi @marph91. That doesn't make sense for me. There is a [github action](https://github.com/HaaLeo/publish-vscode-extension#readme) that will do the job automatically for open-vsx also vscode marketplace.

I'd more like to know if there is some easy way to sync from vscode extension store to openvsx like github actions or cloudflare worker + cron task

**Comment by rxliuli** [comment]
Merged, ref: https://github.com/open-vsx/publish-extensions/pull/640#event-7445746637

**Comment by marph91** [comment]
Thanks! Works with VSCodium 1.71.2.
