### ISSUE TITLE
[Bug]: linux ubuntu 系统中粘贴图片功能无效

### ISSUE THREAD

**Issue by Bailey-24** [rxliuli/joplin-utils#56]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-vscode-plugin

### 您的功能请求是否与问题有关？请描述。

在vscode粘贴的图片无法与joplin同步。
如下图左边是`vscode`粘贴的图片，下图右边的`joplin`中只是显示一串数字，进而在移动端（手机上）也无法显示。
下图的右边`joplin`的第三张图是我自己在`joplin`在粘贴的图片，可以直接显示图片，并且在手机上也能看到
![image](https://user-images.githubusercontent.com/72083251/190861186-36cdf7c6-ce19-452c-bd44-25d8f323afb0.png)

我的设备信息
Ubuntu20.04
同步是的joplin的坚果云web服务

### 描述您想要的解决方案

我觉得应该是文件路径的关系

在`joplin-vscode-plugin`中的图片文件代码为`![1663421899239](image/testst1/1663421899239.png)`
而在原版的`joplin`中图片代码为`![521edd1b8de8a58522b8268e3afa1a6b.png](:/5eae3085df9140bf948a76470dcb74b7)`

区别在于小括号前面有个`:`路径，我觉得这是`joplin`能同步文件里的图片关键因素。

### 描述您考虑过的替代方案

不是很清楚`joplin`同步文件里图片的机制，这也是我第一次用能同步文件的笔记软件，所以没有想法。

**Comment by rxliuli** [comment]
你是否使用了 vscode 的富文本 markdown 编辑器插件？吾辈怀疑是它自行处理了图片而没有经过 joplin-vscode-plugin

**Comment by Bailey-24** [comment]
是的，我刚刚发现我用了`office viewer`这个插件。现在已经卸载了，但是新问题是我直接截图在vscode操作，它完全不是Markdown的图片格式，就只是说`image.png`完全没有图片。

![image](https://user-images.githubusercontent.com/72083251/190862172-7f2dddc2-3bb1-455c-b1af-707c70e86f5c.png)
不是很清楚什么原因
我现在在vscode的Markdown插件只有三个
![image](https://user-images.githubusercontent.com/72083251/190862243-62bdfae1-0819-4a7a-8b23-7d7835f2a6d8.png)

**Comment by rxliuli** [comment]
> 是的，我刚刚发现我用了 `office viewer` 这个插件。现在已经卸载了，但是新问题是我直接截图在 vscode 操作，它完全不是 Markdown 的图片格式，就只是说 `image.png` 完全没有图片。
> 
> ![image](https://user-images.githubusercontent.com/72083251/190862172-7f2dddc2-3bb1-455c-b1af-707c70e86f5c.png) 不是很清楚什么原因 我现在在 vscode 的 Markdown 插件只有三个 ![image](https://user-images.githubusercontent.com/72083251/190862243-62bdfae1-0819-4a7a-8b23-7d7835f2a6d8.png)

ctrl+v 吾辈记得似乎不能正确处理图片，而且这是 vscode 本身的行为，试试 `ctrl+alt+u` 能否粘贴剪切版的图片

**Comment by rxliuli** [comment]
相关文档：https://joplin-utils.rxliuli.com/zh/joplin-vscode-plugin/guide/feature.html#%E5%BF%AB%E6%8D%B7%E9%94%AE

**Comment by Bailey-24** [comment]
我试了一下`ctrl+alt+u`还是不能用，所以我明天早上再根据文档找一下原因。谢谢，祝好梦:）

**Comment by rxliuli** [comment]
> 

如果可以，请帮忙确认一下是否存在快捷键冲突，步骤是

1. 截图并复制到剪切板
2. 在 vscode 中打开一个笔记
3. 输入命令 `joplin upload image from clipboard`，如果看到添加了图片，那么继续下一步，否则是剪切板图片上传发生错误了
4. 输入命令 `open keyboard shortcuts` => 点击录制按键 => 按下 `ctrl+alt+u`

然后，晚安 (￣o￣) . z Z

**Comment by Bailey-24** [comment]
早上好，我试了很久，发现卡在第三步，就是 > 剪切板图片上传错误。
我试过的方法：用插件[picgo](https://juejin.cn/post/6844903974517080071)，它上传图片的快捷键也是`ctrl+alt+u`，但还是不能用。
下面是我的自定义快捷方式。
![image](https://user-images.githubusercontent.com/72083251/190882882-69bb35d4-9424-4985-8c70-04a7eec72d66.png)
下面是从剪切板上传图片的快捷键
![image](https://user-images.githubusercontent.com/72083251/190882922-cd36a830-7497-416d-8038-e784a84e4eb8.png)
就算把joplin的`ctrl+alt+u`换成别的快捷键，如`ctrl+alt+y`，也是不能用。
![image](https://user-images.githubusercontent.com/72083251/190882963-65f43131-7c5f-4982-946d-2cb71baaee57.png)

**Comment by rxliuli** [comment]
> 早上好，我试了很久，发现卡在第三步，就是 > 剪切板图片上传错误。 我试过的方法：用插件[picgo](https://juejin.cn/post/6844903974517080071)，它上传图片的快捷键也是`ctrl+alt+u`，但还是不能用。 下面是我的自定义快捷方式。 ![image](https://user-images.githubusercontent.com/72083251/190882882-69bb35d4-9424-4985-8c70-04a7eec72d66.png) 下面是从剪切板上传图片的快捷键 ![image](https://user-images.githubusercontent.com/72083251/190882922-cd36a830-7497-416d-8038-e784a84e4eb8.png) 就算把joplin的`ctrl+alt+u`换成别的快捷键，如`ctrl+alt+y`，也是不能用。 ![image](https://user-images.githubusercontent.com/72083251/190882963-65f43131-7c5f-4982-946d-2cb71baaee57.png)

请删除掉相同快捷键的其他操作，即第二个截图中的 picgo 插件的

**Comment by Bailey-24** [comment]
已经禁用`picgo`插件，而且在`keybindings.json`文件中删除了粘贴图片相关的操作。
但还是不能用。而且在上面的第三步快捷键为`ctrl+alt+y`，我无法直接在下面第一张图修改快捷键为`ctrl+alt+u`，即按住了`ctrl+alt`再按`u`没有反应。我是在`keybindings.json`文件中修改的joplin粘贴图片快捷键为`ctrl+alt+u`的。
![image](https://user-images.githubusercontent.com/72083251/190883414-3bcedb91-604c-4ec2-81af-bb0c7f33ffa4.png)
![image](https://user-images.githubusercontent.com/72083251/190883420-caa42151-3581-44c2-975a-5ab1593a9934.png)

**Comment by rxliuli** [comment]
等等，那直接输入命令使用 `ctrl+shift+p` 然后 `joplin upload image from clipboard` 可以添加剪切板图片么？如果不行，那么就不是快捷键的问题了

**Comment by Bailey-24** [comment]
> 使用 ctrl+shift+p 直接输入命令 然后 joplin upload image from clipboard 可以添加剪切板图片么
不行。
> 请继续确认 ctrl+shift+e 是否可以从文件选择器的选择添加的图片
可以。
如何解决剪切板图片读取的问题？

![test1](https://user-images.githubusercontent.com/72083251/190884462-ad0213b6-20a7-4578-9fae-025a02548c9a.gif)
![test2](https://user-images.githubusercontent.com/72083251/190884547-ca9b489e-1af1-4e91-8c2c-991cf4136b18.gif)

**Comment by rxliuli** [comment]
> > 使用 ctrl+shift+p 直接输入命令 然后 joplin upload image from clipboard 可以添加剪切板图片么
> > 不行。
> > 请继续确认 ctrl+shift+e 是否可以从文件选择器的选择添加的图片
> > 可以。
> > 如何解决剪切板图片读取的问题？
> 
> ![test1](https://user-images.githubusercontent.com/72083251/190884462-ad0213b6-20a7-4578-9fae-025a02548c9a.gif) [ ![test1](https://user-images.githubusercontent.com/72083251/190884462-ad0213b6-20a7-4578-9fae-025a02548c9a.gif) ](https://user-images.githubusercontent.com/72083251/190884462-ad0213b6-20a7-4578-9fae-025a02548c9a.gif) [ ](https://user-images.githubusercontent.com/72083251/190884462-ad0213b6-20a7-4578-9fae-025a02548c9a.gif) ![test2](https://user-images.githubusercontent.com/72083251/190884547-ca9b489e-1af1-4e91-8c2c-991cf4136b18.gif) [ ![test2](https://user-images.githubusercontent.com/72083251/190884547-ca9b489e-1af1-4e91-8c2c-991cf4136b18.gif) ](https://user-images.githubusercontent.com/72083251/190884547-ca9b489e-1af1-4e91-8c2c-991cf4136b18.gif) [ ](https://user-images.githubusercontent.com/72083251/190884547-ca9b489e-1af1-4e91-8c2c-991cf4136b18.gif)

看起来上传 api 调用没有问题，但无法正常读取剪切板图片，这涉及到一些 mac 的原生脚本，吾辈没有 mac 测试起来有点麻烦，晚点看看怎么测试一下，相关脚本: <https://github.com/rxliuli/joplin-utils/blob/master/apps/joplin-vscode-plugin/src/util/clipboard/mac.applescript>

**Comment by Bailey-24** [comment]
这不是mac，这是Ubuntu20.04

**Comment by rxliuli** [comment]
> 这不是mac，这是Ubuntu20.04

抱歉，那相应的脚本是 <https://github.com/rxliuli/joplin-utils/blob/master/apps/joplin-vscode-plugin/src/util/clipboard/linux.sh>

**Comment by rxliuli** [comment]
或许你可以上传一下日志？通过命令 `joplin open log directory` 打开日志目录压缩 .log 文件为 zip 上传一下

**Comment by Bailey-24** [comment]
下面是打开你给的命令，只有两个文件：combined.log和error.log
[log.zip](https://github.com/rxliuli/joplin-utils/files/9593010/log.zip)
下面是上好几级目录的logs
[logs.zip](https://github.com/rxliuli/joplin-utils/files/9593012/logs.zip)

**Comment by Bailey-24** [comment]
谢谢作者写出这么棒的插件，但是我发现一个更加适合我的笔记软件。所以需要关闭这个issue，请在有空时回复一下 :)
