### ISSUE TITLE
[Feat]: 使「检查未使用的资源」的删除功能可以涵盖本地的加密文件

### ISSUE THREAD

**Issue by Eciclo1239** [rxliuli/joplin-utils#57]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-batch-web

### 您的功能请求是否与问题有关？请描述。

在使用了「检查未使用的资源」功能之后，可以一键删除所有未使用的资源。但是，如果启用了Joplin的端到端加密，附件所在的文件夹（即 配置文件目录\resources）下除了附件之外还有名字相同而后缀为`.crypted`的加密文件，而在一键删除之后，虽然附件本身在本地和同步目标都删除了，但是加密文件仍在本地保存着。

### 描述您想要的解决方案

希望一键删除和普通的删除功能也能将需要删除的附件对应的加密文件也删除掉。

### 描述您考虑过的替代方案

无

**Comment by rxliuli** [comment]
通过 API 删除附件但没有清理对应的加密文件这似乎是 joplin 的 bug，请在 joplin issue 中报告

**Comment by Eciclo1239** [comment]
好的，感谢说明。
