### ISSUE TITLE
[Feat]: Command to Link Other Notes Into Text Area

### ISSUE THREAD

**Issue by globalhuman** [rxliuli/joplin-utils#58]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

In the joplin app a plugin exists to support linking other notes in the text using the key-sequence @@

https://github.com/roman-r-m/joplin-plugin-quick-links

### Describe the solution you'd like

It would be great if there was a command which allows inserting a markdown link to another note such that it presents:

- Most recent notes at the top of the list
- Accepts a search query to find the notes of mention
- Possibly accepts linking to headings/anchors contained within the note

### Describe alternatives you've considered

There currently exists the functionality to "copy link" to create a markdown link to the current note, or from the joplin viewer panel another note. This would be great functionality if possibly to integrate with the @@ sequence as a snippet, or as a command which accepts a shortcut.

**Comment by rxliuli** [comment]
> 

I'd probably try to avoid adding support for the new syntax features of the markdown editor, but maybe add a shortcut that pops up an input box where you can search for a note and insert a link at a specified location in the current editor. In addition, it is interesting to list the reference notes of the current note and the notes that reference the current note through the command, but I don't use note links very much, so it has not been implemented.

**Comment by globalhuman** [comment]
A shortcut/command would be great!

I see the issue with adding new syntax features as you've mentioned. VSCode itself should one day be able to handle command execution from snippets so when a user types `@@` I can link that to command `joplinNote.searchLinks` for example. https://github.com/microsoft/vscode/issues/10561

**Comment by rxliuli** [comment]
Fixed, ref: <https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.9.0>

**Comment by globalhuman** [comment]
How awesome, thanks. I will test it out today!
