### ISSUE TITLE
[Feat]: Note content search inside vscode

### ISSUE THREAD

**Issue by globalhuman** [rxliuli/joplin-utils#59]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

I use vscode Joplin extensively however I still occasionally need to revert back to the app for functionality such as searching where I need to scan through multiple matches. The search feature `Joplin: Search` inside vscode is a handy tool but not being able to visualise the results makes it difficult to use sometimes.

### Describe the solution you'd like

It would be amazing if it was possible to take advantage of the vscode search functionality, or an equivalent inside the Joplin sidebar menu. Having the ability to see the results as I am searching will greatly improve access to information. It will allow a greater deal of flexibility when searching such as using the built in regex etc. I understand that those tools are available to files indexed by vscode, so unless there's a way to have those files indexed it might be a difficult problem. 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/38127975/197897223-2483e739-3a01-4357-858f-2da3a28a6087.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/38127975/197897252-8bfc852d-94b7-410a-93d8-3dfce08033b7.png">

### Describe alternatives you've considered

It is possible to search for content inside notes that are currently opened by vscode. Opening up a series of notes and using the search tool is an option. However, sometimes it's not possible to know where to find the note in the first place.

Another suggestion could be to improve the `Joplin: Search` to have similar functionality to the inbuilt vscode `cmd+P` search files tool. With this tool it's possible to open multiple matching files at the same time using the arrow keys to navigate and the `right` key to open the file. Once all the files are opened then I can use the inbuilt vscode search tool. This is a workaround and not ideal, but an improvement still

**Comment by rxliuli** [comment]
It is possible to search the actual situation, the intellectual method is self-defining webview, and the search function and the search key that can be retrieved from the joplin, and must be searched immediately to some kind of high-performance.
 However, when searching, it is very simple to open multiple options, and there are many types of information that can be handled by demand, so we will see this first.

**Comment by rxliuli** [comment]
fixed, ref: https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%401.2.0
