### ISSUE TITLE
[Question]: How to exclude or ignore all notes inside a notebook from some extensions

### ISSUE THREAD

**Issue by serranomorante** [rxliuli/joplin-utils#60]
# Confirmation

- [x] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

# The tool/kit related to this post

joplin-vscode-plugin

# Describe the question

I have a notebook where I store all my **clipped** markdown pages.

![Joplin notebooks](https://i.postimg.cc/ZngnDyxX/Code-20221027-193306-394.png)

I want to exclude all these notes from extensions like [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) and [spell right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) because I don't need markdown linting or spell checking on web clippings. Neither notebook name nor filename works.

![vscode settings](https://i.postimg.cc/Cx8SS2wZ/Code-20221027-192426-600.png)

Things I have tried without success:
- "!\*\*/Pages/\*\*"
- "!\*\*/web\*" `because I have a file starting with web in its filename`

How can I exclude all those files inside this notebook?

**Comment by rxliuli** [comment]
Right now, you are legally excluded from a specific book, because you own the original md document and have the same title.  However, it is possible to exclude the property of joplin.

**Comment by serranomorante** [comment]
> Right now, you are legally excluded from a specific book, because you own the original md document and have the same title. However, it is possible to exclude the property of joplin.

Sorry I don't understand ;(

Thank you for the quick reply!

**Comment by rxliuli** [comment]
> > Right now, you are legally excluded from a specific book, because you own the original md document and have the same title. However, it is possible to exclude the property of joplin.
> 
> Sorry I don't understand ;(
> 
> Thank you for the quick reply!

I updated the response a bit, in short I don't think it's currently possible to ignore a directory in joplin because it doesn't actually exist locally

**Comment by serranomorante** [comment]
Thank you!
