### ISSUE TITLE
[Feat]: 读取joplin笔记本标题作为categories变量

### ISSUE THREAD

**Issue by cnlnn** [rxliuli/joplin-utils#64]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-blog

### 您的功能请求是否与问题有关？请描述。

使用joplin-blog生成的md文件中只有如下变量，没有categories变量
```
---
layout: post
title: This is Title
abbrlink: 767322ef9e3147eeaf76fedbd39b5a0b
tags:
  - tag
date: 1669465898313
updated: 1669468991738
---
```
而我使用的hexo主题需要categories变量才能让文章分类

### 描述您想要的解决方案
使用joplin的笔记本作为categories变量的值
![image](https://user-images.githubusercontent.com/24188176/204091776-89acd383-870c-4979-9d81-9376ac8eabea.png)
在md文件头生成如下变量
```
---
layout: post
title: This is Title
abbrlink: 767322ef9e3147eeaf76fedbd39b5a0b
categories:
  - 笔记
tags:
  - tag
date: 1669465898313
updated: 1669468991738
---
```

### 描述您考虑过的替代方案

无

**Comment by rxliuli** [comment]
那 categories 的值应该是什么呢？另外目前 joplin-blog 已被移至 @mami/cli，参考：https://github.com/rxliuli/mami/blob/master/README.zh-CN.md

请在那边提 issue：https://github.com/rxliuli/mami/issues

**Comment by cnlnn** [comment]
> 好的，已使用mami在index.js添加categories后解决问题

```
function addMeta(root, note) {
  setYamlMeta(root, {
    layout: "post",
    title: note.title,
    abbrlink: note.id,
    categories: note.path,
    tags: note.tags.map((item) => item.title),
    date: note.createAt,
    updated: note.updateAt
  });
}
```

**Comment by rxliuli** [comment]
> 好的，已使用 mami 在 index.js 添加 categories 后解决问题
> 
> ```
> function addMeta(root, note) {
>   setYamlMeta(root, {
>     layout: "post",
>     title: note.title,
>     abbrlink: note.id,
>     categories: note.path,
>     tags: note.tags.map((item) => item.title),
>     date: note.createAt,
>     updated: note.updateAt
>   });
> }
> ```

看起来这是一个合理的默认值，我稍后会将它添加到 [@mami/plugin-hexo](https://github.com/rxliuli/mami/tree/master/packages/plugin-hexo) 的默认值中

**Comment by rxliuli** [comment]
> > 好的，已使用 mami 在 index.js 添加 categories 后解决问题
> > ```
> > function addMeta(root, note) {
> >   setYamlMeta(root, {
> >     layout: "post",
> >     title: note.title,
> >     abbrlink: note.id,
> >     categories: note.path,
> >     tags: note.tags.map((item) => item.title),
> >     date: note.createAt,
> >     updated: note.updateAt
> >   });
> > }
> > ```
> 
> 看起来这是一个合理的默认值，我稍后会将它添加到插件 [@mami/plugin-hexo](https://github.com/rxliuli/mami/tree/master/packages/plugin-hexo) 的默认值中

已修改，如果你愿意，可以尝试 [@mami/plugin-hexo@0.5.4](https://www.npmjs.com/package/@mami/plugin-hexo)

**Comment by cnlnn** [comment]
> > > 好的，已使用 mami 在 index.js 添加 categories 后解决问题
> > > ```
> > > function addMeta(root, note) {
> > >   setYamlMeta(root, {
> > >     layout: "post",
> > >     title: note.title,
> > >     abbrlink: note.id,
> > >     categories: note.path,
> > >     tags: note.tags.map((item) => item.title),
> > >     date: note.createAt,
> > >     updated: note.updateAt
> > >   });
> > > }
> > > ```
> > 
> > 
> > 看起来这是一个合理的默认值，我稍后会将它添加到插件 [@mami/plugin-hexo](https://github.com/rxliuli/mami/tree/master/packages/plugin-hexo) 的默认值中
> 
> 已修改，如果你愿意，可以尝试 [@mami/plugin-hexo@0.5.4](https://www.npmjs.com/package/@mami/plugin-hexo)

十分感谢，现已使用[@mami/plugin-hexo@0.5.4](https://www.npmjs.com/package/@mami/plugin-hexo)进行博客部署
