### ISSUE TITLE
[Feat]: generate table of contents when [TOC] is present

### ISSUE THREAD

**Issue by danielb2** [rxliuli/joplin-utils#66]
### app

joplin-vscode-plugin

### Description

plugin to generate table of contents from markdown when [TOC] is present like native joplin would

### Describe alternatives you've considered

manually generate table of contents with another vscode plugin

**Comment by rxliuli** [comment]
Have you tried the markdown-all-in-one plugin, it already supports something similar. ref: https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#table-of-contents

**Comment by danielb2** [comment]
Yes, that's the alternative I've considered. Still requires manually generating a TOC which it then keeps up todate. Of course, then when i use joplin, it will not be kept up to date there

**Comment by rxliuli** [comment]
Well, if you're just for viewing, maybe you don't have to render the toc in html, vscode itself provides similar functionality.

ref: https://code.visualstudio.com/docs/languages/markdown#_document-outline
![image](https://user-images.githubusercontent.com/24560368/210284703-d346b08b-ddc3-4a3b-89be-eb78882d8585.png)

In addition, it is indeed a bit strange. I did a simple search, but I did not find a vscode extension that supports this syntax. Isn’t it some existing standard? Or is it only supported in joplin?

**Comment by danielb2** [comment]
The outline is a good workaround, thanks

> Isn’t it some existing standard? Or is it only supported in joplin?

Not that I'm aware. I've seen some variants of it before tho, for example, I believe some wiki engine had `%toc%`

**Comment by danielb2** [comment]
btw, I recommend two extensions in addition to the ones you have...

- [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)
- [Mermaid Markdown Syntax Highlighting](https://marketplace.visualstudio.com/items?itemName=bpruitt-goddard.mermaid-markdown-syntax-highlighting)

between the two, the vscode plugin acts even more like joplin. It's getting to the point where this plugin is almost like JOplin itself which is why I thought the `[TOC]` was missing

**Comment by danielb2** [comment]
@rxliuli  not sure you see the msgs after it's been closed

**Comment by rxliuli** [comment]
Maybe support for joplin's toc syntax can be added at some point, but since there are already alternatives, it won't be a high priority

**Comment by silopolis** [comment]
@danielb2 I believe the `[TOC]`, or `[[TOC]]` which also seems to work in Joplin, tag is supported by either the Markdown Extended extension or the Markdown Extended Preview one.

**Comment by danielb2** [comment]
> @danielb2 I believe the `[TOC]`, or `[[TOC]]` which also seems to work in Joplin, tag is supported by either the Markdown Extended extension or the Markdown Extended Preview one.

interesting. I had been using the more popular `All in one markdown` which doesn't have this supported. thanks for this
