### ISSUE TITLE
[Bug]: token/port setting is ignored

### ISSUE THREAD

**Issue by vasaka** [rxliuli/joplin-utils#67]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

I am getting `Joplin's token/port is set incorrectly, unable to access Joplin service! Are you sure it is running and active?` error

When opening developer tools I see following error in the console 
`FetchError: request to http://127.0.0.1:41184/ping?token= failed, reason: connect ECONNREFUSED 127.0.0.1:41184`

the plugin ignores both my custom port and address and token I have added in the settings, when I try to connect to ping in browser with correct token and port it is all works just fine

### Steps to reproduce the behavior

Install the plugin
Go to extension settings
Set token and custom url
Restart VS Code
Try open Joplin side bar
Observe Joplin's token/port is set incorrectly error

Go to Help/Toggle Developer Tools
Go to console tab
Observe error message `FetchError: request to http://127.0.0.1:41184/ping?token= failed, reason: connect ECONNREFUSED 127.0.0.1:41184` that ignores the plugin settings

### log file

logs are empty
[combined.log](https://github.com/rxliuli/joplin-utils/files/10338155/combined.log)
[error.log](https://github.com/rxliuli/joplin-utils/files/10338156/error.log)

**Comment by rxliuli** [comment]
Ok, I confirmed the problem, can you try the new version? I will use the configuration in vscode when pinging

[joplin-vscode-plugin-1.1.1.zip](https://github.com/rxliuli/joplin-utils/files/10341184/joplin-vscode-plugin-1.1.1.zip)

**Comment by vasaka** [comment]
It works now, thanks
