### ISSUE TITLE
[Feat]: add searx for supported search engine

### ISSUE THREAD

**Issue by sabinich** [rxliuli/joplin-utils#68]
### app

joplin-search-integration-plugin

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

hello, @rxliuli!
Your plugin for Joplin, which helps integrate search request is amazing! I've wait it for a long time!
Can you add self-hosted meta-search system search for Joplin Search Integration? 

### Describe alternatives you've considered

no

**Comment by rxliuli** [comment]
> ### app
> joplin-search-integration-plugin
> 
> ### Is your feature request related to a problem? Please describe.
> no
> 
> ### Describe the solution you'd like
> hello, @rxliuli! Your plugin for Joplin, which helps integrate search request is amazing! I've wait it for a long time! Can you add self-hosted meta-search system search for Joplin Search Integration?
> 
> ### Describe alternatives you've considered
> no
> 
> ### Additional context
> _No response_

Well, you brought up a topic I'm interested in, but I don't use the joplin server, not sure if it exposes a public search api, or it's just used inside joplin, so it's not listed on the joplin website.

**Comment by rxliuli** [comment]
It seems impossible to connect directly to the joplin server, ref: https://discourse.joplinapp.org/t/19374/9
But maybe you can run a joplin cli client on the remote side, then expose its joplin clipper service port to the public network, and finally connect to this client

**Comment by sabinich** [comment]
@rxliuli Hello. You are wrong. I said about **[searx](https://github.com/searx/searx)**, not about Joplin server.

**Comment by rxliuli** [comment]
> @rxliuli Hello. You are wrong. I said about **[searx](https://github.com/searx/searx)**, not about Joplin server.

Yes, I read it wrong, I will look at how to integrate and expose settings to users
urls: https://searx.space/

**Comment by rxliuli** [comment]
Added a Pre Release, can you try it?

ref: https://github.com/rxliuli/joplin-utils/releases/tag/joplin-search-integration%400.3.0

**Comment by sabinich** [comment]
@rxliuli Hello! I checked this. But seems like, that it works only with `https://searx.tiekoetter.com/`. I tried on other public instances, but it not work. Also on my private instance it not work too,

**Comment by rxliuli** [comment]
> @rxliuli Hello! I checked this. But seems like, that it works only with `https://searx.tiekoetter.com/`. I tried on other public instances, but it not work. Also on my private instance it not work too,

Are there any non-working instances that are publicly accessible?

**Comment by rxliuli** [comment]
I checked and it seems that some searx searches are not putting the query parameter on the url parameter, I made some fixes, can you try again?

[chrome.zip](https://github.com/rxliuli/joplin-utils/files/10379293/extension.zip)

**Comment by sabinich** [comment]
I've found few searx-instances, which not worked with firefox extenstion:

- https://opnxng.com/
- https://s.frlt.one/
- and mine private instance 

But some first from list—works well.

**Comment by rxliuli** [comment]
I'm sure already supports <https://s.frlt.one/>, Both chrome and firefox are
![image](https://user-images.githubusercontent.com/24560368/211802681-d084a9c3-bc94-48b0-a40f-434bb81e5403.png)

Did you not configure SearxUrls?
![image](https://user-images.githubusercontent.com/24560368/211802833-26580cf9-f6bf-4786-9f10-89aa7b113771.png)

**Comment by rxliuli** [comment]
I just released 0.3.2, it will now try to auto-discover the searx search engine, no more configuration, ref: https://github.com/rxliuli/joplin-utils/releases/tag/joplin-search-integration%400.3.2

**Comment by sabinich** [comment]
Now everything is fine! Thanks, @rxliuli !

**Comment by rxliuli** [comment]
> Now everything is fine! Thanks, @rxliuli !

ok, I'll post a chrome/firefox extension later
