### ISSUE TITLE
[Feat]: add support for MetaGer searchengine

### ISSUE THREAD

**Issue by MoriarT3a** [rxliuli/joplin-utils#70]
### app

joplin-search-integration

### Is your feature request related to a problem? Please describe.

In Germany we have a datasecurity based searchengine called MetaGer. I would like to see MetaGer as an searchprovider for the joplin-search-integration.

### Describe the solution you'd like

Add MetaGer.de as  searchengine.

### Describe alternatives you've considered

I could use duckduckgo otherwise. But i would like to see metager.de. :-)

### Additional context

There is a Websearch-Widget to use on your own website. Maybe it is usefull for you.
https://metager.de/websearch/

**Comment by rxliuli** [comment]
Release 0.4.0, ref: https://github.com/rxliuli/joplin-utils/releases/tag/joplin-search-integration%400.4.0
