### ISSUE TITLE
[Bug]: vscode有两个所见即所得的插件无法显示图片

### ISSUE THREAD

**Issue by zjinc36** [rxliuli/joplin-utils#72]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

这个可能只能算半个bug，或者可以认为是功能请求。

vscode有两个插件`office viewer`和`vscode all markdown`，打开普通的markdown文件没有问题，但打开joplin的markdown文件不显示图片。

- 打开普通的markdown文件

![image](https://user-images.githubusercontent.com/33741027/226823972-7a6d99ec-9001-4962-9c11-402c207c55d7.png)

- 打开joplin的markdown文件

![image](https://user-images.githubusercontent.com/33741027/226824176-df0c35a7-7ecd-4aa6-952c-53ddf9f05457.png)

应该是和如何认识图片地址的方式有关，有办法解决吗？

### Steps to reproduce the behavior

1. 安装上述任意一个插件
2. 在vscode中打开joplin的带图片的markdown文件就能重现

### log file

无

**Comment by rxliuli** [comment]
这是预期的，markdown 中的链接都需要经过 joplin 插件渲染，如果其他插件自定义了渲染逻辑，则图片以及链接都将不可用，该插件无法与所见即所得的插件配合，但与 markdown all in one 这个插件可以协同的很好。
