### ISSUE TITLE
[Bug]: Links to headers not working

### ISSUE THREAD

**Issue by vsabarly** [rxliuli/joplin-utils#73]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

Thanks for developing this very useful plugin.

I have an issue when I click on an internal header link, I get the following error: `The file is not displayed in the text editor because it is a directory`.

### Steps to reproduce the behavior

1. Create a test note:
```
# Test

[link to title](#title)

## title
```
2. Follow the link by (Cmd or Ctrl) clicking on `#title`
3. See the error

### log file

combined.log:
```
{"level":"info","message":"joplin config, baseUrl: http://localhost:41184, token: string","pluginVersion":"1.1.1"}
{"level":"info","message":"command execute: joplinNote.openNote","pluginVersion":"1.1.1"}
{"level":"info","message":"openNote start, id: d667628587784e97a444a591e49df404, title: Test","pluginVersion":"1.1.1"}
{"level":"info","message":"openNote write tempFile: Test.md","pluginVersion":"1.1.1"}
{"level":"info","message":"openNote open tempFile","pluginVersion":"1.1.1"}
```

Nothing in error.log

### Additional context

If the note is already opened when VS Code starts, header links are working (you can test by restarting without closing the test note).

**Comment by rxliuli** [comment]
Fixed, please update to 1.1.2, or wait for the VSCode plugin to be automatically updated
ref: https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%401.1.2
