### ISSUE TITLE
[Bug]: Plugin cannot reconnect if Joplin wasn't running at first attempt

### ISSUE THREAD

**Issue by michalfita** [rxliuli/joplin-utils#74]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

If I run VS Code and then Joplin and then jump to the extension everything works. But If I open VS Code where the extension is remembered as open and then open Joplin there's no option to reconnect. This is serious flaw. I have to close VS Code to reconnect the plugin to the Joplin's server.

### Steps to reproduce the behavior

Actually already described above:
1. Run VS Code with extension open
2. Run Joplin
3. No option to reconnect to the server and Refresh fails that action is not available

### log file

Calling for mentioned option end up as well with error:
![image](https://github.com/rxliuli/joplin-utils/assets/4925040/0bb0b520-9817-42cf-9da3-0f181bfbf640)

### Additional context

Looks like the extension is dead if it didn't manage to connect to the server.

**Comment by rxliuli** [comment]
Fixed, released v1.1.3
https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%401.1.3
