### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by synckey** [rxliuli/joplin-utils#75]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-vscode-plugin

### 您的功能请求是否与问题有关？请描述。

我有两台设备，每个上面都有joplin，但是token不一样，目前这个插件只支持设置一个token，这样在如果我设置了a设备的token，这个token会被自动同步到b设备上，但是又访问不了b上的Joplin，不知道有没有麻烦解决。

### 描述您想要的解决方案

支持设置多个token，自动探测哪个是有效的？

### 描述您考虑过的替代方案

vscode 支持按照机器设置 token.

**Comment by rxliuli** [comment]
不需要，你可以修改 joplin 的 token，具体的配置文件在  ~/.config/joplin-desktop/settings.json 中，修改其中的 api.token 为同一个即可

**Comment by synckey** [comment]
多谢
