### ISSUE TITLE
Create a new feature to scan and update the internal Joplin note's title link.

### ISSUE THREAD

**Issue by Eduardo3382** [rxliuli/joplin-utils#76]
### app

joplin-batch-web

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Create a process for scanning and renaming an internal Joplin title notes, when the user changing title notes that has included in internal links.

### Describe alternatives you've considered

The idea is to scanning all the links and backlink and compare them with the current title note that include in the Joplin's links and rename with the current name when any does not match it. 
Similar process used for "Check for unused resources" and based on the Laurent suggestion https://discourse.joplinapp.org/t/renaming-internal-note-links-when-renaming-note/17580/3

### Additional context

N/A

**Comment by rxliuli** [comment]
I added a new Fix internal link Title page for checking and bulk updating inconsistent link titles, can you try it?  (be sure to backup before any bulk operation, and check after)

ref: https://joplin-utils.rxliuli.com/web/joplin-batch-web/#/fixInternalLinkTitle

![image](https://github.com/rxliuli/joplin-utils/assets/24560368/bddcc1b8-3984-4b32-aa66-c96dbede2f94)

**Comment by Eduardo3382** [comment]
@rxliuli 
The link working very well. I had several inconsistencies and in all the cases, update with the current title. Excellent!!!!!
Note: This process does not recognize the link created at the internal header, when the user installed and using the plug-in [joplin-plugin-copy-anchor-link](https://github.com/hieuthi/joplin-plugin-copy-anchor-link). I do not know if this is possible to consider to check as well, or at least it should be better to include in any note to be aware to the user about this limitation.

**Comment by rxliuli** [comment]
Sure, I'll try to support this kind of link later

**Comment by Eduardo3382** [comment]
When you review the 'Fix internal link Title' process for updating title links when there is a discrepancy in the title note link 
in the case, the link is created through the 'joplin-plugin-copy-anchor-link,' 
I'd like to bring an additional minor matter to your attention. 
I noticed that when the note link is generated by the 'note-overview-plugin,' although the note title link is updated automatically, 
I found that if a user accidentally or intentionally adds a hashtag (#) within the title, your process identifies this title as one to be fixed, even if the current title is accurate.
In my case, I added a hashtag to the title by mistake so, I was able to rectify removing the (#) from the title. 
I'm mentioning this minor issue for your consideration, in case you would like to examine and address it as well."

**Comment by rxliuli** [comment]
> I noticed that when the note link is generated by the 'note-overview-plugin,' although the note title link is updated automatically,

This behavior is intentional, since note titles should always be stripped starting with # , which is a duplicate statement.

**Comment by rxliuli** [comment]
Supported

<img width="578" alt="image" src="https://github.com/rxliuli/joplin-utils/assets/24560368/42c54691-e0e4-408a-8850-39bd4bcb3dae">
