### ISSUE TITLE
[Feat]: Support direct webdav access

### ISSUE THREAD

**Issue by showgood163** [rxliuli/joplin-utils#78]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

Joplin client supports direct webdav access and manages files accordingly. Can this plugin do the same?

### Describe the solution you'd like

This plugin can support direct webdav access (and behaves like a joplin client).

### Describe alternatives you've considered

I don't know. Maybe this is too far-fetched for a plugin?

**Comment by rxliuli** [comment]
Do you mean view and manage all attached resources? This is indeed a new feature. But I would like to know in what scenario do you usually use this function? Clean up unused resources?

**Comment by showgood163** [comment]
> Do you mean view and manage all attached resources? This is indeed a new feature. But I would like to know in what scenario do you usually use this function? Clean up unused resources?

1. Yes. I mean use vscode and this plugin to replace the joplin client.
2. My webdav server is very weak (armv5 level cpu) and I dont want to setup full joplin-server on that.

**Comment by rxliuli** [comment]
Oh, I want to double check what you mean. Do you mean using the vscode plugin without installing the joplin client at all? This is probably not possible, at least a cli client needs to be installed, this plugin relies on the client's web clipper api. But it might be useful to provide attachment resource management, I'll look at adding a list to the sidebar.

**Comment by showgood163** [comment]
> Do you mean using the vscode plugin without installing the joplin client at all?

Yes.

> at least a cli client needs to be installed

Can you show me some cli clients for windows?

**Comment by rxliuli** [comment]
> > Do you mean using the vscode plugin without installing the joplin client at all?
> 
> Yes.
> 
> > at least a cli client needs to be installed
> 
> Can you show me some cli clients for windows?

ref: https://joplinapp.org/terminal/ . Note that I'm not actually using the cli client, but it is officially supported by joplin.

**Comment by showgood163** [comment]
> ref: https://joplinapp.org/terminal/ .

Thanks. I'll see what I can do.
