### ISSUE TITLE
[Bug]: markdown文档无法用 Markdown-Preview-Enhanced 插件打开预览

### ISSUE THREAD

**Issue by rockyzhz** [rxliuli/joplin-utils#81]
### 确认事项

- [X] 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### 发生错误的工具/包

joplin-vscode-plugin

### 描述这个错误

给出的错误是：

`notebookPath`: "file:///c%3A/Users/%E5%BC%A0%E6%B3%93%E7%9F%A5/AppData/Roaming/Code/User/globalStorage/rxliuli.joplin-vscode-plugin" must be an absolute path

这个是不是修改一下文件的路径表示？

### 复现错误的步骤

在 VS Code 里安装一下 Markdown-Preview-Enhanced 试试看哈，我印象中是有这么回事的。

### 日志文件

貌似没有啊

**Comment by rxliuli** [comment]
不兼容这个插件，FAQ 中最后一项有写
https://joplin-utils.rxliuli.com/zh/joplin-vscode-plugin/guide/faq.html#markdown-%E9%A2%84%E8%A7%88%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E5%9B%BE%E7%89%87

**Comment by rxliuli** [comment]
另外是重复的
https://github.com/rxliuli/joplin-utils/issues/46

**Comment by rockyzhz** [comment]
> 不兼容这个插件，FAQ 中最后一项有写 https://joplin-utils.rxliuli.com/zh/joplin-vscode-plugin/guide/faq.html#markdown-%E9%A2%84%E8%A7%88%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E5%9B%BE%E7%89%87

哦哦，但是我使用了 Markdown All in One 这个插件的Preview功能（Ctrl+Shift+V），出现了同样的错误提示。
