### ISSUE TITLE
[Feat]: 能否在侧边栏添加一些菜单项?

### ISSUE THREAD

**Issue by gaoqiangks** [rxliuli/joplin-utils#86]
### 确认事项

- [ ] 我愿意实现它

### 您运行的是我们软件的哪个版本？

joplin-vscode-plugin

### 您的功能请求是否与问题有关？请描述。

![image](https://github.com/rxliuli/joplin-utils/assets/52161883/a98631b8-7428-47a0-badc-f814d61dc5f8)

比如在这个地方添加 "新建笔记"  "新建待办事项"? 

### 描述您想要的解决方案

添加一些菜单, 使得插件更加易用

### 描述您考虑过的替代方案

暂无

**Comment by rxliuli** [comment]
右键菜单中包含此功能
