### ISSUE TITLE
[Bug]: 安裝code spell checker插件後自動換行的字數超出頁面

### ISSUE THREAD

**Issue by 2ipm1nd** [rxliuli/joplin-utils#88]
### 确认事项

- [X] 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### 发生错误的工具/包

joplin-vscode-plugin

### 描述这个错误

安裝code spell checker前每行約50欄就能自動換行，安裝後會變成100欄左右才會自動換行，請問有什麼辦法更改為50欄左右換行嗎？
joplinnote.showlogfiledir

### 复现错误的步骤

1. 安裝joplin-vscode-plugin
2. 安裝code spell check
3. 點選joplin-vscode-plugin內的md檔會錯亂
4. 點選本機的md檔正常

### 日志文件

無顯示

**Comment by rxliuli** [comment]
按照复现步骤安装完插件未复现问题，是否可以提供一个错误演示视频？

**Comment by 2ipm1nd** [comment]
抱歉……我重開vscode之後就正常了，目前使用完全沒問題，感謝您的回覆。
