### ISSUE TITLE
[Feat]: Create note from selection

### ISSUE THREAD

**Issue by silopolis** [rxliuli/joplin-utils#89]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

Restructuration, splitting notes and contents is one of the main activities after writing, and sometimes before when working with the web clipper.

### Describe the solution you'd like

The ["Create note from highlighted text" Joplin plugin](https://discourse.joplinapp.org/t/create-note-from-highlighted-text/12511) does a fantastic job.
Same features would be awesome.

### Describe alternatives you've considered

Usual old school cut+create note+paste

### Additional context

Implementation of these features into the VSCode plugin would greatly smooth daily life and would be, AFAIC, a big step toward a Joplin as backend only setup and workflow.

**Comment by rxliuli** [comment]
It looks interesting, but I don’t have high-frequency needs. vscode itself supports multiple tabs (multiple notes can be opened at the same time) and can arrange windows side by side. I think part of the problem has been solved?

**Comment by silopolis** [comment]
Well, not really...

The difference in the flow (number of keystrokes/commands) is already a significant one, to wich is added the **automatic creation of the link** from the source document to the newly created one.

This last one is a game changer! It allows for rapid restructuring/document splitting with simple and fast sequences of 'select > ctrl+alt+N [> edit new note] > ctrl+w'.

Without having to:
* cut the content to split from the source note
* create new note
* paste content in new note
* copy title of the new note
* paste the title back into the source note
* chase the new note URL,
* copy the URL,
* Create the link in the source note

Generally, I make structuration work before, then edit the splits. This feature alone is so efficient and makes me save so much time that I keep returning to Joplin just for that.
This makes my standard workflow: capture with clipper > structure/split in Joplin > edit in VScode.

It'd be great if I only had to alt+tab between FF and Codium :)

**Comment by rxliuli** [comment]
Release 1.6.0, ref: https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%401.6.0

**Comment by silopolis** [comment]
Holly you!
Can't wait to get the release pop via Open-VSX...
Thank you so much for this. It comes very timely as Joplin's slowness has started playing badly with my nerves. :/

PS: BTW, maybe you could claim your namespace [there](https://open-vsx.org/extension/rxliuli/joplin-vscode-plugin) to remove the ugly warning banner :)
