### ISSUE TITLE
docs: Document optimization progress

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/joplin-utils#9]
- [x] Add documentation on how to contribute
- [x] Need to translate and proofread how to share related documents (due to the **knowledge curse**, it is difficult for me to find some problems that may arise from non-developers)
- [x] joplin-vscode-plugin: English translation needs to be touched up, most of the previous ones were machine translated
- [x] The prompt information of joplin-blog cli, specifically: <https://github.com/rxliuli/joplin-utils/blob/master/apps/joplin-blog/src/i18n/en.json> -- deprecated
- [x] joplin-blog: need to add Chinese and English documentation, the main goal is to make it available to non-developers -- deprecated
  - [x] zh-CN
  - [x] en-US
- [x] joplin-batch-web: English translation needs to be added
- [x] joplin-search-integration: not working on this side for now, can be a bit later
- [x] joplin-api: need to add Chinese api documentation
- [x] joplin-vscode-plugin: Description of existing joplin plugin in vscode as an alternative plugin or function
  - Special pastes (e.g. csv)
  - vim editor -- vim plugin
  - notes outline sidebar -- panel with shortcuts or sidebar
  - Formatting -- prettier
  - Persistent folding in the editor -- vscode default support
  - Template functionality -- vscode default support
  - diff comparison -- supported by vscode by default
  - math mode -- natively supported by vscode
  - rich markdown -- plugins
  - Editor Layout -- natively supported
  - Expanding panels -- html code snippets are fine

**Comment by Daeraxa** [comment]
>     * [ ]  joplin-blog: need to add Chinese and English documentation, the main goal is to make it available to non-developers 
>       * [x]  zh-CN
>       * [ ]  en-US

Was going to start on this but it seems the Chinese documentation isn't finished in some places - namely this document - https://joplin-utils.rxliuli.com/zh/joplin-blog/guide.html

>     * [ ]  joplin-batch-web: English translation needs to be added

Currently working on this one

**Comment by rxliuli** [comment]
> Was going to start on this but it seems the Chinese documentation isn't finished in some places - namely this document - https://joplin-utils.rxliuli.com/zh/joplin-blog/guide.html

Yes, this is the same as contributing to the project. It is very simple for development but may be more complicated for general users (mainly preconditions). I am not sure how to write the documentation here.

**Comment by rxliuli** [comment]
> > Was going to start on this but it seems the Chinese documentation isn't finished in some places - namely this document - https://joplin-utils.rxliuli.com/zh/joplin-blog/guide.html
> 
> Yes, this is the same as contributing to the project. It is very simple for development but may be more complicated for general users (mainly preconditions). I am not sure how to write the documentation here.

I tried to add a document, but I'm not sure if it has any omissions for ordinary people

**Comment by Daeraxa** [comment]
I'll give it a test run, I kind of sit in the middle of technical and ordinary. At the very least it can be translated "as is" and improved later but I'll have a look to see where things might not be clear and propose some changes (in english) to the translated docs in the PR. I'll mark what I've added and you can review and edit the originals or reject the changes as required.
