### ISSUE TITLE
[Feat]: Add Brave search engine for both Brave and Chrome browsers

### ISSUE THREAD

**Issue by jbenninghoff** [rxliuli/joplin-utils#90]
### app

joplin-search-integration

### Is your feature request related to a problem? Please describe.

joplin-search-integration works in Brave if I use Google search but not if I use Brave search.

### Describe the solution you'd like

Just add support for Brave search.

### Describe alternatives you've considered

I saw the suggestion for adding the code myself but I'm not familiar with the code or language.

### Additional context

Very useful feature for Joplin users with hundreds of notes like myself.

**Comment by rxliuli** [comment]
The latest version 0.6.0 is supported. If you have any questions, please report them in time.

<img width="1389" alt="image" src="https://github.com/rxliuli/joplin-utils/assets/24560368/2f1e39f2-a36f-4598-876c-69355b252c96">

release: https://github.com/rxliuli/joplin-utils/releases/tag/joplin-search-integration%400.6.0
