### ISSUE TITLE
[Feat]: Add a setting to expand search to note bodies

### ISSUE THREAD

**Issue by jbenninghoff** [rxliuli/joplin-utils#91]
### app

joplin-search-integration

### Is your feature request related to a problem? Please describe.

Current Joplin search integration is limited to Joplin note subjects and ids.  Joplin full notes search is fairly quick, at least on my machines.  It would be nice if the body of all the notes could be searched too. 

### Describe the solution you'd like

 It could be enabled through a plugin option setting.

### Describe alternatives you've considered

Not applicable

**Comment by rxliuli** [comment]
I'm not sure what you're talking about, but the integrated search should be no different from the search within the Joplin application itself.
