### ISSUE TITLE
[Bug]: Search integration with Brave using search.brave.com no longer working

### ISSUE THREAD

**Issue by jbenninghoff** [rxliuli/joplin-utils#92]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-search-integration

### Describe the bug

search integration output appears briefly then disappears on Brave browser using search.brave.com.  Shields are down for site.

### Steps to reproduce the behavior

Search for something using Brave and google.com and make sure Joplin note(s) appears in results.
Search for same keyword using Brave and search.brave.com.  Nothing appears but loading message appears briefly.
This worked in some prior version of Brave and possibly older version of plugin.

### log file

Where do I run the suggested command?

### Additional context

Version of Brave:
[Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (arm64)](https://brave.com/latest/)
Version of plugin:
0.6.2

**Comment by rxliuli** [comment]
Brave search seems to be broken, but Google is working fine, even when using Google in the Brave browser.
