### ISSUE TITLE
[Bug]: Windows Search Indexer keeps running when there is no edit action

### ISSUE THREAD

**Issue by wdhongtw** [rxliuli/joplin-utils#93]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

Every time when I have this extension enabled in VS Code, the Search Indexer keep consuming CPU resources, even when
I do not opening any note in VS Code.

![image](https://github.com/rxliuli/joplin-utils/assets/16065489/ebb11935-5935-4d46-8c23-b9feae41a456)

Based on the output of process monitor, it seems that this extension will trigger Joplin to append log to log file,
and trigger the action in Search Indexer indirectly.

![image](https://github.com/rxliuli/joplin-utils/assets/16065489/ad5c57df-a2ba-4eba-9a58-2bbcca2bc0b1)

I'm not sure this can be considered as a bug by this extension, but this phenomenon do bother me a little. :(

I'm wordering if there is anything we can do to reduce the CPU consumption of Search Indexer when using extension?

Environment:

- Joplin: v2.14.19
- Extension: v1.4.1

### Steps to reproduce the behavior

1. Install this extension and setup the access token
2. Open Joplin and VS Code with this extension enabled

### log file

The error log contains no content.

**Comment by rxliuli** [comment]
Yes, the extension will call the Joplin Webclipper's API to refresh the note tree in VSCode, but I didn't know there would be such an obvious waste of performance on Windows... Maybe, I guess you can temporarily solve this by excluding this directory from the Windows search index?

**Comment by wdhongtw** [comment]
Thanks for your quick response!

> you can temporarily solve this by excluding this directory from the Windows search index

This is a resonable solution, and it do works for me. (I add `C:\Users\<username\.config` folder)

I think I should close this issue now... If we need to do something, we can open this issue later. :D
