### ISSUE TITLE
[Feat]: 希望增加搜索分词功能以改进Joplin笔记内容检索能力

### ISSUE THREAD

**Issue by dark2star** [rxliuli/joplin-utils#94]
### app

joplin-search-integration

### Is your feature request related to a problem? Please describe.

如题，因为Joplin笔记自身搜索使用类模糊查找实现，导致用户搜索笔记效果较差，往往检索不到一条内容，经测试后发现使用分词后效果比之前好很多。

### Describe the solution you'd like

可采用分词器在插件端实现用户搜索关键词的分词功能，分词后传给joplin

### Describe alternatives you've considered

引入本地分词器插件

**Comment by rxliuli** [comment]
让吾辈先找 joplin 作者确认一下对 cjk 的支持是否可以直接放到 joplin 程序内部实现。
https://discourse.joplinapp.org/t/joplins-vscode-plugin-is-released/9624/119

**Comment by dark2star** [comment]
> 让吾辈先找 joplin 作者确认一下对 cjk 的支持是否可以直接放到 joplin 程序内部实现。 https://discourse.joplinapp.org/t/joplins-vscode-plugin-is-released/9624/119

好的👍，如果他们可以解决那太好了

**Comment by dark2star** [comment]
> > 让吾辈先找 joplin 作者确认一下对 cjk 的支持是否可以直接放到 joplin 程序内部实现。 https://discourse.joplinapp.org/t/joplins-vscode-plugin-is-released/9624/119
> 
> 好的👍，如果他们可以解决那太好了

我试了其他的笔记Obsidian，也存在这个问题，此类问题应该客户端不像服务端那样使用es、solr这样的检索引擎可以做全文检索，中文搜索词被当成整体去进行模糊搜索造成的，官方改起来的时间一般会很长且充满了不确定性
