### ISSUE TITLE
[Feat]:  search tags and notebooks

### ISSUE THREAD

**Issue by sardnar** [rxliuli/joplin-utils#95]
### app

joplin-vscode-plugin

### Is your feature request related to a problem? Please describe.

I can find no way to search for tags in the extension

### Describe the solution you'd like

either similar to joplin, use @/# to search for tags or notebooks. Or even better to have overall fuzzy search in all headlines, body and tags from the search 

### Describe alternatives you've considered

.

**Comment by rxliuli** [comment]
Joplin search tag document, ref: https://joplinapp.org/help/apps/search

tag:	Restrict the search to the notes with the specified tags.	tag:office searches for all notes having tag office.
tag:office tag:important searches for all notes having both office and important tags.
tag:office -tag:spam searches for notes having tag office which do not have tag spam.
any:1 tag:office tag:spam searches for notes having tag office or tag spam.
tag:be*ful does a search with wildcards.
tag:* returns all notes with tags.
-tag:* returns all notes without tags.
