### ISSUE TITLE
[Bug]:  Images may get lost after being edited visually in Joplin.

### ISSUE THREAD

**Issue by h2dcc** [rxliuli/joplin-utils#98]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

On the Bug Report page, the option "The tool/kit where the error occurred" does not include "joplin-publisher." The main issue arises with the plugin at [https://github.com/rxliuli/joplin-utils/releases/tag/joplin-publisher%401.0.0](https://github.com/rxliuli/joplin-utils/releases/tag/joplin-publisher%401.0.0)

 Since Joplin supports a visual editor, some images may be converted from the default Markdown syntax to HTML syntax during adjustments. After publishing to GitHub using the Joplin Publisher plugin, these images using HTML syntax will be lost.

Orginal image:
`![](:/142970433a904c2aa33d3447aff5df9e)`

Edited visually in Joplin:
`<img src=":/142970433a904c2aa33d3447aff5df9e" alt="4aabb661d6b056257e104529374d71eb.png" width="902" height="550">` 

### Steps to reproduce the behavior

1. Open a note using the Joplin APP in Windows.
2. Click on the switch Editor in the top right corner.
3. Adjust the size of the images within the note.
4. Go to Tools - Publish to GitHub.

### log file

no log file

**Comment by rxliuli** [comment]
> ### Confirmation
> * [x]  I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)
> 
> ### The tool/kit where the error occurred
> joplin-vscode-plugin
> 
> ### Describe the bug
> On the Bug Report page, the option "The tool/kit where the error occurred" does not include "joplin-publisher." The main issue arises with the plugin at https://github.com/rxliuli/joplin-utils/releases/tag/joplin-publisher%401.0.0
> 
> Since Joplin supports a visual editor, some images may be converted from the default Markdown syntax to HTML syntax during adjustments. After publishing to GitHub using the Joplin Publisher plugin, these images using HTML syntax will be lost.
> 
> Orginal image: `![](:/142970433a904c2aa33d3447aff5df9e)`
> 
> Edited visually in Joplin: `<img src=":/142970433a904c2aa33d3447aff5df9e" alt="4aabb661d6b056257e104529374d71eb.png" width="902" height="550">`
> 
> ### Steps to reproduce the behavior
> 1. Open a note using the Joplin APP in Windows.
> 2. Click on the switch Editor in the top right corner.
> 3. Adjust the size of the images within the note.
> 4. Go to Tools - Publish to GitHub.
> 
> ### log file
> no log file
> 
> ### Additional context
> _No response_

Currently, parsing and handling HTML is not supported, maybe later.
