### ISSUE TITLE
Check for unused resources: Out of memory

### ISSUE THREAD

**Issue by nonobio** [rxliuli/joplin-utils#99]
Hi,

I just did [a deletion of thousands of notes](https://discourse.joplinapp.org/t/after-deleting-thousands-of-notes-how-do-i-finish-cleaning/38863) and from what I see, the resources were not deleted.
I then came across this tool which seems to meet my needs, thank you :)

However, it shows me Out of memory:
![image](https://github.com/rxliuli/joplin-utils/assets/7425799/8c94f657-8c4f-4c01-b3a7-bf2bdace7326)
Is there something I'm doing wrong?

Thanks :)

**Comment by rxliuli** [comment]
It might be that loading all the attachment resources at once is consuming too much memory.

**Comment by nonobio** [comment]
After doing a huge cleanup in Joplin, I used the tool again and it worked without problems, thanks :)

**Comment by rxliuli** [comment]
> After doing a huge cleanup in Joplin, I used the tool again and it worked without problems, thanks :)

Just today, I released the plugin version of this tool. It can be used on desktop or mobile devices, and has already implemented the functions of cleaning up attachment resources and global search and replace. You might be interested in it.

![image](https://github.com/user-attachments/assets/b71a0d17-0048-4d53-aa0d-4cd66fbcc29a)

https://joplin-utils.rxliuli.com/en-US/joplin-batch/

**Comment by nonobio** [comment]
Great, thanks :)
